Scripts/NagiosChecks/autoreduce_checklastrun.py

This PR adds more detail to the output of the checklastrun nagios script.
- The name of the instrument that failed.
- The last run number in the database and the last run number in lastrun.txt.
Also if one instrument fails it no longer exits and instead continues checking all instruments.
Closes #33

More detailed checklastrun nagios messages

---

.gitignore
setup.py

* Add a basic setup.py file that can be used with pip install -e to initialise the python path for the project and allow for absolute imports.
* small tidy up to ignore migration files in project (these are generated when creating the test database)
* Test on local machine
* Run `pip install -e autoreduce` from the parent directory of the autoreduce project.
* Ensure the command executes as expected
* Ensure that you can perform absolute imports in the project
Fixes #34

add setup py file

---

.gitignore
Scripts/Build/generate_apache_wsgi.py
WebApp/autoreduce_webapp/apache/apache_django_wsgi.conf.template

* Changed file wsgi file to template on git
* Created script to generate wsgi file from command line input
*This should form part of the general build script once it's implemented*
* Checkout the code on webapp dev node.
* Copy the `Webapp/autoreduce_webapp/apache/apache_django_wsgi.conf` to a different location outside the project.
* Delete the apache_django_wsgi.conf *(this will have to be done manually this time as it is now in the git ignore)*
* Generate the new apache_django_wsgi.conf using the script (usage instructions are in the docstring).
* Stop the webapp service and ensure you can no longer access it
* Start the webapp service (this should now be using the conf file) 
* Check you can access the webapp
* Delete the copy of …

Add generation script for apache_django_wsgi.conf

---

QueueProcessors/QueueProcessor/queue_processor.py
QueueProcessors/QueueProcessor/utils/reduction_run_utils.py

- Django stores datetime information in UTC in the database for reasons listed [here](https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/), however the queue processor was simply using `datetime.now()` causing jobs **not** submitted through the web app to be an hour out.
- This PR just changes `datetime.now()` to `datetime.utcnow()` in the queue processor.
- Restart the queue processors 
- Submit a job using the manual submission script 
- Check the times displayed on the web app are correct for that job
- Re-submit a job on the web app
- Check the times displayed on the web app are correct for that job
Fixes #22 
---
**To test**
* Log into the devolpement nodes
* `git checkout this-pull-request-branch`
* restart services on each node …

Fix incorrect times being displayed on web app 

---

QueueProcessors/restart.sh

* The restart.sh script should now be callable from any location
* If the queues are not running (can't find `.pid`) restart will start them
* Stop daemons and try to use restart to start them - this should work
* Try to restart the queues while it's running - this should work
* Try to use the script from any location (don't `cd` into `QueueProcessors` folder)

Improve QueueProcessor restart.sh

---

WebApp/autoreduce_webapp/reduction_viewer/models.py

- Allow the `overwrite` attribute of a reduction run to be null.
- Fixes issue with a newly migrated database not working with queue_processor. An exception was being thrown when queue processor tried to insert a reduction run with the overwrite attribute null.

Allow overwrite to be null

---

EndOfRunMonitor/ISISendOfRunMonitor.py

- Improve logging in end of run monitor
- Puts the monitor_log.txt directly on the C drive.
Restart end of run monitor and check log for output.
Doesn't fix #59 as the STOMP will still be noisy logging, haven't got time to investigate and fix this currently.

Improve logging in end of run monitor

---

WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py

Sets the testing settings to enable debug mode by default, so Django can serve content in lieu of Apache (which is used on production)
- With a fresh cloned repository follow the local setup instructions
- Attempt to open the page, the static content should not load in
- Checkout these changes
- Run `migrate_test_settings.sh`
- The static content should now load
Fixes #82 
---
**To test**
* Log into the devolpement nodes
* `git checkout this-pull-request-branch`
* restart services on each node (information on how to do this can be found in the development documentation)
* Submit some runs with the manualsubmission.py script
Once you are happy, merge this pull request into develop, and update the development nodes to the devlop branch
```
> git …
```

Set testing builds to debug mode by default

---

.travis.yml
QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
Scripts/ManualSubmissionScript/manual_submission.py
requirements.txt
setup.py

* Move project requirements to install requires
* Run `pip install -e autoreduction` (from parent directory of the project) and ensure that the  pip requirements are checked/ installed.
* This should also work with `python setup.py install`
* Ensure that the build still passes on travis (with new build instructions)

Move project requirements to setup.py

---

WebApp/autoreduce_webapp/reduction_viewer/models.py
WebApp/autoreduce_webapp/reduction_viewer/utils.py

- Adds validators to the model for better error reporting in the stack traces
- Reworks control flow so we don't attempt to save a record before a clean. 
- This could still fail a FK constraint on the DB side. So instead of attempting to delete the record (which will lose our trace) that wasn't saved, we let Django fail the entry.
- We let the database sort by version, instead of parsing each record and using max to achieve the same effect.
- We now catch specific exceptions, rather than the kitchen sink approach.
- Go to reduction_viewer\utils.py:112
- Change the line that reads: `run_version=last_version + 1` to `run_version='a'`.
- Check a sane stack trace and error message are printed
- Examine the stack trace, it should have failed on …

Add validators to model and perform clean before saving

---

Documentation/Technical Documentation.md
WebApp/autoreduce_webapp/reduction_viewer/utils.py

Changes the current helper methods in `utils` from `get_or_create` to `get`. This should prevent accidental creation of new records in the database
- Navigate to `/instrument/MUSR/variables/` - if this loads correctly the changes work (as it relies on `get_instrument` and `get_status` to work
- Navigate to `/instrument/foo/variables/` - the old code would create an entry in the DB. This should throw a does not exist record
Fixes #94 
---
**To test**
* Log into the devolpement nodes
* `git checkout this-pull-request-branch`
* restart services on each node (information on how to do this can be found in the development documentation)
* Submit some runs with the manualsubmission.py script
Once you are happy, merge this pull request into develop, and …

Remove get_or_create in models

---

WebApp/autoreduce_webapp/autoreduce_webapp/urls.py

- A simple change to allow negative RB numbers in the URL. Negative RB's are often used for calibration runs. 
- Check that you can access an experiment with a negative RB number, for example GEM RB-1000
- Check that you can still access an experiment with a positive RB number.
Fixes #107 
---
**To test**
* Log into the devolpement nodes
* `git checkout this-pull-request-branch`
* restart services on each node (information on how to do this can be found in the development documentation)
* Submit some runs with the manualsubmission.py script
Once you are happy, merge this pull request into develop, and update the development nodes to the devlop branch
```
> git checkout origin/devlop
> git fetch -p
> git pull origin/develop
```

Allow negative RB numbers in WebApp

---

QueueProcessors/AutoreductionProcessor/post_process_admin.py
QueueProcessors/AutoreductionProcessor/settings.py.template

- Reduced data can no longer be saved on the ISIS archive, it all goes to CEPH
- This also means new instruments will not need adding to `ceph_instruments` in the queue processor settings files. The `excitation_instruments` setting still remains as their data is saved in a different format (No run number folders)
- Submit a non-excitation (defined in `QueueProcessors/AutoreductionProcessor/settings.py`)  instrument reduction job 
- Check it the reduced data gets saved with the correct directory strucure
- Reduced data should be contained in a run number directory. e.g. `/instrument/GEM/RBNumber/RB1720007/autoreduced/84854/`
- Submit an excitation instrument reduction job
- Check the reduced data gets saved with the correct folder structure (No …

Remove saving to archive feature

---

build/tests/test_pylint.sh

The migrations files are auto generated and hence should be ignored by pylint

Remove pylint checks for migrations files

---

QueueProcessors/AutoreductionProcessor/autoreduction_processor.py

revert some changes made in QueueProcessor to use Client as they are not quite working. It's safer at this point during release cycle to revert instead. This should be fixed properly in 18.3
*No associated issue*

Fixes to queue processor

---

WebApp/autoreduce_webapp/templates/snippets/run_variables.html

Original issue found during smoke testing
This issue ensures that the reduction variables that get passed to the server side validation are named correctly. Previous a name mis-match caused the variable to not be found in the POST content. 
* Run the webapp
* Click on a run (note: if this run is already queued in another job this will not pass validation)
* Expand the `Re-run reduction job` tab
* Add a sensible name in the `Re-run description` field (e.g. `validate #174 is resolved`)
* Click the `Re-run with new variables`
* Ensure that this validates (receive message about run submitted successfully)
* Ensure that the run appears in the `All jobs` page and reduces successfully
Fixes #174

Webapp: Ensure that reduction variables naming convention

---

QueueProcessors/QueueProcessor/queue_processor.py

This PR detects experiments with string RB numbers and stops them from passing further through the pipeline. Reduction runs started directly after a calibration experiment are then able to successfully complete.
Fixes #179

Skip calibration experiments

---

WebApp/autoreduce_webapp/test_files/syntax_error/reduce.py
WebApp/autoreduce_webapp/test_files/syntax_error/reduce_vars.py
build/tests/test_pylint.sh

Remove two unused test files to reduce the pylint score. Despite the skip-file flag being in the offending file, these still raise an error in pylint as they have syntax errors in them

Remove unused test files for syntax error

---

monitors/end_of_run_monitor.py
monitors/icat_monitor.py
monitors/test_settings.py
monitors/tests/test_icat_monitor.py

ICAT checker that accepts as input an element from the INSTRUMENTS list and returns the latest run number from that instrument according to ICAT. The list of instruments can be found in the test_settings.py of the monitors directory.
I also expanded logging so it includes the log level, file name and line number in both EoRM and the ICAT checker. I think this will make it easier to track down bugs.
A 'file_prefix' attribute has been added to the instrument dictionary because not all instruments prefix their files with the full name of the instrument. e.g. 'MERLIN' and 'MER'
* Run the unit tests. No special configuration is required to do this.
* Run icat_monitor.py against a real ICAT. It should print out the latest run number for each instrument in the INSTRUMENTS list. This can be …

ICAT Checker for EoRM

---

monitors/tests/test_icat_monitor.py

The `get_last_run` function in the icat_monitor is currently untested. This PR adds tests for this although they mainly use mock.patch for regression testing. This should increase the get_last_run coverage to 100%
Fixes #214

Add test coverage to get_last_run 

---

utils/clients/icat_client.py
utils/clients/tests/test_icat_client.py

* Added multiple tests for the icat client
* Had to use plenty of `mock.patch` for this to remove the dependency on ICAT 
* Ensure unit tests work
* Review code to ensure that the mocking is sensible
Fixes #101

Add tests for icat client

---

monitors/end_of_run_monitor.py
scripts/manual_submission_script/manual_submission.py
scripts/manual_submission_script/tests/test_manual_submission.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

Move the data serialisation to the queue client. The unit tests should be enough to validate that this change is successful
Fixes #140

Move serialisation to queue client

---

.coveragerc
.gitignore
monitors/end_of_run_monitor.py
monitors/health_check.py
monitors/tests/test_end_of_run_monitors.py
monitors/tests/test_health_check.py

This should increase test coverage in the end of run monitor package to 100% for all files except the win_service file which can not be tested on linux. We can add test coverage for this once we have a travis  windows build.

Increase test coverage in the monitors package

---

monitors/health_check.py

The logging in the Health check for the end of run monitor is a bit too noisy. This should reduce the logging output by half and make the logs a little cleaner

Reduce logging from Health check

---

monitors/health_check.py
monitors/tests/test_health_check.py

Ensure that we are not resubmitting the first entry that is already in the database. The updates to the tests show that this will avoid a resubmission.

Remove resubmit of first run from EoRM health check

---

monitors/health_check.py

Commit results each time a database query is made. This resolves the issue where the database last run number would not update due to reuse of the uncommitted session object.
Run end of run monitor and ensure the last run number from the database updates.

Committed after performing query

---

QueueProcessors/AutoreductionProcessor/autoreduction_logging_setup.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/help.html
WebApp/autoreduce_webapp/templates/run_summary.html
build/database/populate_reduction_viewer.sql

Add a link to the ceph data storage area for users to download their data. This link is currently available via the run summary page
* Open the webapp to the run summary page ensure that the link takes you to the right place (try this with several different runs) 
Fixes #236

CEPH link in webapp

---

utils/data_archive/archive_explorer.py
utils/data_archive/data_archive_creator.py
utils/data_archive/tests/test_archive_explorer.py
utils/data_archive/tests/test_data_archive_creator.py

* Added ability to create `reduce.py` and `reduce_vars.py` to a fake data archive via the use of the `DataArchiveCreator`
* Added the ability to search for `reduce.py` and `reduce_vars.py` in a data archive via the `ArchiveExplorer`
* Code review
* Check the instructions in #266
This is blocking continuation of #28 
Fixes #266

DataArchiveCreator reduce.py and reduce_vars.py

---

WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py

Modified code to authenticate with the user office after their update that deprecates certain methods.
Turn off ```DEVELOPMENT_MODE``` in the web app settings files. Ensure that the development WSDL and user office site are being used. Then attempt to login to the web app. This will only work on the Autoreduce development machine due to the user office only permitting redirects to certain URLs.
Fixes #265

Change for the user office update

---

monitors/health_check.py

Modified the health checker last run query to order by run number rather than created date. This causes problems when an old run is resubmitted, leading the health checker to wrongly assert that the database is behind ICAT.
Resubmit an old run and check to make sure the health checker uses the latest run number.
Fixes #273

Order database runs by run number

---

monitors/tests/test_health_check.py

* Updated test expected values to match what we expect
* Ensure the unit tests pass of travis
This was fixed prior, but must have been accidentally re-introduced due to a merge conflict
*No associated issue*

Fix test failure introduced due to resolveing merge conflict

---

WebApp/autoreduce_webapp/autoreduce_webapp/icat_communication.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/experiment_summary.html

* Added the use of `django.utils.encoding.smart_str` to ensure that all unicode characters can be correctly decoded.
* The easiest way to test this will be using the development environment webapp.
* Before changing the branch to the fixed code:
* Visit the main `/runs/`
* Click `View By Experiment Number`
* Click an experiment RB number and observe the Experiment Summary page now opens
* If this page has information such as: `Principal investigator` populated, then go back and find an RB number where this information is blank (WISH - RB1910211 is one example on the development environment currently)
* Now you have located an experiment with missing information, change the branch in the local git directory to this one containing the fix. 
* Restart the web app by opening the `services` …

Missing experiment summary information

---

monitors/README.md
monitors/new_end_of_run_monitor.py
monitors/test_settings.py
monitors/tests/test_new_end_of_run_monitor.py
setup.py
utils/clients/queue_client.py

Implementation of the new end of run monitor design.
See updated README file for details on how to setup locally.
Unit tests can be run without any setup. Just type ```pytest test_new_end_of_run_monitor.py```
I have made the cycle folder a setting that has to be manually adjusted. The reason I did this is to minimise the knowledge of the archive that's written into the code itself, this helps with testing because we don't have to go about setting up fake archives. At the same time, I thought it would be too cumbersome to have to adjust the cycle folder on every instrument in the CSV file, so I put it in settings.py. Let me know what you think is best.
I experienced difficulty with the EoRM logging config being overwritten by that of the queue client. That's why I have set up a logger in a …

New End of Run Monitor

---

monitors/new_end_of_run_monitor.py
monitors/tests/test_new_end_of_run_monitor.py

Now searches from the bottom of the summary file. It also looks for the summary run number as a sub-string in the full run number.
Attempt to submit runs for ENGINX or OSIRIS using the new end of run monitor.
Fixes #303

Handle ENGINX summary format

---

QueueProcessors/QueueProcessor/queue_processor.py
QueueProcessors/QueueProcessor/queueproc_utils/messaging_utils.py

Fixed bug where timed reruns would trigger a Python exception due to an import error. This would lead to the run getting stuck in the queued state.
Force a timed rerun by adding the following line to post_process_admin.py _send_error_and_log
```
self.data['retry_in'] = 1
```
Then submit a run that fails. You will see on the master branch that it just remains in the queued state, whereas on this branch the run goes through and repeatedly errors.
Simple fix after finding the relevant log lines and a way to reproduce.
Fixes #272

Fixed bug with timed reruns only reaching 'Queued' state

---

WebApp/autoreduce_webapp/templates/run_summary.html

Added a date to the error messages displayed on the run summary page. I assume that the error is generated when the run is marked as finished.
Load a failed run in the webapp and see that the date is correctly displayed.
Fixes #294

Added date to error messages on the run summary page

---

monitors/new_end_of_run_monitor.py
monitors/tests/test_new_end_of_run_monitor.py

Instrument summary files do not follow a well defined format, so there is a chance that the end of run monitor will encounter a case where it can't locate the correct run number. Rather than getting stuck on a run and being unable to move on, it should just select the last run as the most likely to be applicable.
I have added a unit test for this case. It can be tested manually by making a copy of a summary file and removing an entry. Then point your lastruns.csv to this file and attempt to submit a run, check that it just submits the last entry.
Fixes #310

Default to using the last row in the summary file

---

.gitignore
.travis.yml
WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
build/commands/migrate_settings.py
utils/test_credentials.ini
utils/test_settings.py

* Add an `.ini` file that holds all the credentials for services
* update build script to move test `.ini` file
* Run `python setup.py test_settings` from the root directory of the project
* Enter valid credentials into the `utils/credentials.ini`
* I would suggest trying this with local settings first then development settings
* Run the webapp: python Webapp/autoreduce_webapp/manage.py runserver
* Check it is using the expected settings
* Use manual submission to submit a run
* Ensure this run appears in the webapp (the 2 are using the same settings)
Fixes #320

Credentials file for services

---

monitors/new_end_of_run_monitor.py
monitors/tests/test_new_end_of_run_monitor.py

Now just takes last RB number from the summary file.
Run on the development node and ensure all RB numbers are reported correctly. It should be clear whether it is running correctly after a few days.
Fixes #329

Take last RB number from summary

---

monitors/new_end_of_run_monitor.py
monitors/tests/test_new_end_of_run_monitor.py
setup.py

The new EoRM now loads RB numbers from the Nexus file itself, falling back on the summary file if necessary. The summary file will definitely still be used on instruments that produce HDF4 Nexus files. I considered it not worthwhile to load HDF4 files given that all instruments that use HDF4 are fine with the summary file. Existing libraries that load HDF4 are also quite difficult to setup because they rely on a C++ library underneath.
There is now a wiki entry for testing EoRM locally: https://github.com/ISISScientificComputing/autoreduce/wiki/Testing-the-new-End-of-Run-Monitor
There are two additional dependencies to be installed in the following order:
* numpy
* nexusformat
I have also pulled the new code onto the development node.
Fixes #338

Read RB number from the Nexus file

---

docker_reduction/mantid/Mantid.user.properties

Changed logging level in mantid properties file
None required
The logging of the autoreduction process is actually performed mainly by the reduction script and in part by the post_process_admin.py hence there are no changes to make here that I am aware of.
Fixes #356

Change mantid properties file to log at notice level

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/instrument_summary.html

The default number of items in a page default to 50 and this is represented in the options dropdown
Load the page and see if the dropdown menu corresponds with the number of items in the page by default.
Fixes #358

Default items per page

---

WebApp/autoreduce_webapp/templates/submit_runs.html

* Now informs users that all run numbers must be in the same experiment
* Load the Webapp re-run past jobs page e.g. `webapp-address/instrument/GEM/submit_runs/`
* Hover over the `i` icon on the page and ensure it displays a better help message
* This would be better as validation in the future but will be fine for now
Fixes #48

Improve info message on resubmit field

---

.gitignore
.travis.yml

* Move the travis file to run with xenial ubunutu and python 3
* add python 3 venv names to git ignore
* Ensure that the travis build is using python 3. For this pull request we are not concerned with the tests / pylint passing or failing
Fixes #397

python 3 travis migration

---

queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/queue_processor/queue_processor.py
queue_processors/queue_processor/test_settings.py

* Remove the use of deprecate imp in queue processor
* Remove email functionality from queue processor as it was never used and doesn't appear to work. Furthermore, I don't think we want this functionality

Remove imp and email functionality

---

WebApp/autoreduce_webapp/templates/base.html
WebApp/autoreduce_webapp/templates/fail_queue.html
WebApp/autoreduce_webapp/templates/help.html
WebApp/autoreduce_webapp/templates/instrument_summary.html
WebApp/autoreduce_webapp/templates/instrument_variables.html
WebApp/autoreduce_webapp/templates/navbar.html
WebApp/autoreduce_webapp/templates/outdated_browser.html
WebApp/autoreduce_webapp/templates/overview.html
WebApp/autoreduce_webapp/templates/run_confirmation.html
WebApp/autoreduce_webapp/templates/run_summary.html
WebApp/autoreduce_webapp/templates/submit_runs.html
WebApp/autoreduce_webapp/templates/variables_summary.html

- Replaced all instances of deprecated `staticfiles` tags to their simplified 3.0 equivalent
Solution source: https://stackoverflow.com/questions/55929472/django-templatesyntaxerror-staticfiles-is-not-a-registered-tag-library
Fixes #459 

459 Make code django3 compatible

---

WebApp/autoreduce_webapp/templates/instrument_summary.html

Heading for each control have been put within the control code itself (at the top).
This results in expected layout behaviour when window is narrowed.
- Open the webapp
- Select an instrument
- Decrease the window width
- Ensure the layout remains as expected
This PR negates the need for #461 because the header is put within the control appearance condition
Fixes #465 

Fix narrow window layout issues

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/admin/graph_instrument.html

I've simply cast a return value to an integer.
I presume that an implicit integer conversion was allowed through the old Python version, but no longer allowed in 3.
- Open the web app and sign in as admin (or use the development server / local)
- Click graphs from the top right menu
- Try to generate any of the graphs for the instruments on this page with the Graph button
- All graphs should generate with no issue
Fixes #462

Fix TypeError on WebApp graph request

---

WebApp/autoreduce_webapp/static/javascript/instrument_summary.js
WebApp/autoreduce_webapp/templates/instrument_summary.html

JavaScript for instrument_summary created to resubmit the form when the "Filter by" selection changes.
This causes the python conditions (injected within the HTML) to rerun and thereby redetermine the page structure based on the current field values.
- Open the webapp
- Select an instrument
- Try both _Filter by_ values
- Ensure the page reloads with the expected form elements
- This solution was chosen over adjusting the HTML within the JavaScript based on the "Filter by" value because this would result in duplicated functionality for hiding/showing elements.
- A side effect of this solution choice is that the "Filter by" value is always applied instantly and automatically on selection.
Fixes #464 

Change WebApp form on filtre selection

---

WebApp/autoreduce_webapp/reduction_variables/views.py
WebApp/autoreduce_webapp/reduction_viewer/utils.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
monitors/run_detection.py
monitors/tests/test_run_detection.py
queue_processors/queue_processor/queue_processor.py
queue_processors/queue_processor/queueproc_utils/reduction_run_utils.py
scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
systemtests/test_end_to_end.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

This PR ensures the `started_by` field is populated in all instances of the code where a run can be submitted.
- When a run is submitted via the webapp, the field is populated by the current user_id (tests _3._ and _4._ below).
- When submitted **automatically**, it is populated with a **`0`** (test _2._).
- When submitted **manually**, using the `manual_submission.py` script, it is populated with a **`-1`** (test _1._).
**Example database entries**
id=58540: automatic
id=58549: via webapp (Re-run past jobs) where user_id=1
id=58550: via webapp (Re-run past jobs) where user_id=2
id=58551: via webapp (Re-run reduction job) where user_id=2
1. **Manual:** Submit run using the manual submission script `scripts/manual_operations/manual_submission.py` and ensure that a `-1` has been populated …

Populate started_by field in all cases

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html

This PR adds a Started by field to the run summary.
The value of this field is determined by the value of `run.started_by` through the following conditional flow:
If `run.started_by` is `None` or _<-1_
- The "Started_by" field does not appear.
If `run.started_by` is _-1_
- "Started_by: Development team"
If `run.started_by` is _0_
- "Started_by: Autoreduction service"
If `run.started_by` is _>0_
- "Started by: [first_name] [last name]" _e.g. "Started by: Joe Bloggs"_
- In this case, the value of `started_by` is assumed to be the user id- which is used to retrieve the first and last name from the User database.
- **Note:** If the value of `started_by` does not match a user id: an exception is raised and the code continues as though `started_by = None` (the first condition of this list)
* …

Display "started_by" on WebApp

---

Documentation/release-notes/20-1.md
queue_processors/queue_processor/queue_processor.py

Ensure that RB0 or less AND String RBs are skipped and added to the skipped queue (not just never run)
Manually submit an RB 0, ensure it shows up in the webapp as skipped and has an explanation 
Fixes #451

Skip calibration RBs

---

Documentation/release-notes/20-1.md
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_queue.html
setup.py

- Refactored the code in views.py to have a method that looks up user/team names based on user ID to be used for assigning who submitted a run.
-Changed run_summary() and run_queue() in views.py to use this new method.
-Changed run_queue.html to correctly display the 'submitted by' information on the Run Queue page.
-Created new release notes.
- Set your credentials.ini to point to the development environment start the webapp
- Navigate to (<webapp_address>/runs/GEM/90107/1/) and ensure that the user is stated as Started by: Development team
- Navigate to (<webapp_address>/runs/GEM/90107/) and ensure that the user is stated as Started by: Autoreduction service
- Navigate to (<webapp_address>/runs/GEM/90107/3/) and ensure that the user is stated as Started by: Elliot Oram
-Navigate to …

486 submitted by on job queue page

---

WebApp/autoreduce_webapp/templates/instrument_summary.html

- This PR simply sets the `onClick` attribute of the RB number link (in the instrument summary table when filtred by jobs) to `event.stopPropagation();` 
- This stops the `collapse` toggle from being called instead of the link when the user specifically clicks the link.
- If the user clicks the box around the text, collapse is called instead of the link.
* Open the web app
* Select an instrument
* Change to filter by RB_number
* Click on an RB number and observe that you go to the experiment summary page
* Go back 
* Click around the RB Number (on the row) and ensure it expands the list of runs
Fixes #440

Stop collapse from blocking the RB-number-link

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/experiment_summary.html

- This PR allows the 'Reduction Jobs' count (number within the parentheses) to populate.
- Previously, this would not populate at all
- Navigate to an experiment summary
- Ensure count is populating with the total number of runs
Fixes #496

#496 Move run-count logic to views.py, pass via the context_dict

---

plotting/plot_meta_language/tests/test_prepare_data.py
plotting/prepare_data.py
scripts/tests/__init__.py

- This PR adds a `prepare_data.py` component, along with tests.
- `prepare_data.py` primary function is to load a CSV file from a given path, converts it into a `pandas.DataFrame` and returns this.
- Formats are outlined below:
```
1
1.0, 2.0, 3.0 
4.0, 5.0, 6.0
1.0, 2.0, 3.0
```
_Note:_ Line 1 above specified by instance variable `PrepareData.expected_first_row`
```
|Spectrum | X     | Y   | E   |
| :---    | :---: |:---:| ---:|
| 1       |       |     |     |
| 1       | 1.0   | 2.0 | 3.0 |
| 1       | 4.0   | 5.0 | 6.0 |
| 2       | 1.0   | 2.0 | 3.0 |
```
* Review code
* Run tests: `\plotting\plot_meta_language\tests\test_prepare_data.py`
Fixes #473

Add prepare_data

---

.travis.yml
message/__init__.py
message/job.py
message/tests/__init__.py
message/tests/test_job.py
setup.py

Added a class that can handle the containment of an AMQ message and act as a wrapper to the meta data stored within. The class can also be serialised and un-serialised (whcich must be done before sending.
* Code review
* Assess quality of unit tests
Note: this is not current implemented in the places it will be used in the code base. This is ONLY a review of the containing class for AMQ messages. Integration will be done in a  separate PR and most likely done one area at a time.
Fixes #507 

Basic AMQ message class

---

plotting/plot_meta_language/tests/test_interpreter.py
plotting/tests/test_prepare_data.py

Part of #514
- Docstrings within the test files of the Plotting directory standardised to meet the Test/When format
- Review the updated docstring

Standardise test-docstrings to 'Test/When' for Plotting

---

queue_processors/autoreduction_processor/autoreduction_processor.py
queue_processors/autoreduction_processor/tests/test_autoreduction_processor.py

* Changed the AMQ subscription in the autoreduction_processor to be done via the QueueClient. 
* Perform a manual submission on the development environment (this code is currently on there but might be worth checking before you do this).
* Ensure that the job does not get stuck in the queued state.
* Before merging I might look into cleaning this up a little. There is currently functionality in the QueueClient for subscription but I wasn't able to get this to work initially in this code. As such I will look into if I can get it to work or remove it. 
EDIT: Will wait till I have done the rest of the stomp removing until I make any decisions about this.
Part of #517 

Remove use of raw stomp in autoreduction_processor.py

---

scripts/tests/test_scheduler_ingest.py

Part of #514
- This PR standardises docstrings within test_scheduler_ingest to meet the Test/When format
- Review the updated docstring

Standardise test-docstrings to 'Test/When' for test_scheduler_ingest 

---

utils/clients/tests/test_abstract_client.py
utils/clients/tests/test_cycle_ingestion_client.py
utils/clients/tests/test_database_client.py
utils/clients/tests/test_icat_client.py
utils/clients/tests/test_queue_client.py
utils/clients/tests/test_sftp_client.py

Part of #514
- Docstrings within the test files of the `utils/clients` directory standardised to meet the Test/When format
- Review the updated docstring

Standardise test-docstrings to 'Test/When' for Clients

---

docker_reduction/mantid/tests/test_mantid_docker_container.py

- This PR simplifies the tests for `test_build` and `test_reduce_simple` by mocking the _heavy and slow_ docker.from_env functionality
- Instead of testing that the output of these docker-enabled methods are as expected, the tests now simply check the correct methods are called with the correct arguments leading to the docker functionality
- Additionally, re-formats tests to Test/When
- Code review
- All tests passing (Travis)
- Speed up of Travis
- This PR makes a method used for post-test-clean-up (`_clean_output_directory`) unused: 
Fixes #527

Simplify slow docker tests by mocking

---

WebApp/autoreduce_webapp/static/javascript/tours/navbar-tour.js

- This PR adds a conditional on `navbar-tour.js` to display different copy depending on whether the user is logged in (sees the full navigation bar) or not logged in (just sees 'sign in' prompt).
- Review the copy (content text)
- Ensure the right copy is displayed in both cases: where a user is (i) logged in, and (ii) not logged in
_Note: to test (ii) locally, one method is to change the `navbar.html` condition `if user.is_authenticated` (screenshot) to `if False`_
Fixes #536

Amend Navbar tour step content

---

scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py

- This PR changes the _data file location & RB-number retrieval_ functionality (fka `get_data_file`) of the `manual_submission` script (MSS) to first check the Auto-reduction database (i.e. check whether the file has already been reduced) before resorting to calling ICAT for this information.
- This avoids unnecessary ICAT calls and enhances autoreduction's (AR) independence from ICAT
- Ensure the following cases are true (which can be checked by the print statements produced):
1. When a file exists in AR, MSS retrieves the necessary data from there
2. When a file does not exists in AR, MSS calls ICAT
3. When a file exists in neither AR or ICAT, MSS exits gracefully as usual
- I've used raw SQL because we plan to change our ORM soon.
* It is easier to transition from raw SQL to a new ORM …

Manual Submission to check DB before calling ICAT

---

.travis.yml
queue_processors/autoreduction_processor/autoreduction_processor.py
queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/autoreduction_processor/tests/test_autoreduction_processor.py
queue_processors/autoreduction_processor/tests/test_post_process_admin.py
queue_processors/queue_processor/queue_processor.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

- This PR adjusts `post_process_admin.py` and `autoreduction_processor.py` to only use QueueClient methods, and not save and use the underlying stomp connection.
- It contains several notes questions of how to develop this PR further.
- Review and respond to `Note:` comments
- Review code thus far
Fixes #543

Replace storage and use of ._connection outside of QueueClient

---

message/job.py
queue_processors/queue_processor/tests/test_queue_processor.py
scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

- This PR begins the task of Integrating the Message class into the code base (#512)
- Specifically, this PR does the following:
* Updates `QueueClient.send` to accommodate Message instances being received as the message argument (as well as json dumps which have been use up until now)
* Adds logging to the Message class such that when `populate` encountered a key which does not match an attribute, a warning is logged
* Refactors the `manual_submission` call to `QueueClient.send` to use the Message class instead of a json dump (+ tests)
* Adds a test for a usage of `QueueClient.send` that was missed.
* note: there is another usage in the same class but it is within the 100-line `data-ready` method.  Due to it's size, adding tests to this method should be separate chunk of work.
- Ensure …

Integrate Message class to manual_submission

---

monitors/run_detection.py
monitors/tests/test_run_detection.py

- This PR continues integrates the Message class  into `run_detection`
- This is done by replacing the data dictionary used to pass run data with a Message instance
- Tests are refactored to accommodate the change
- Additionally, this change renders `build_dict` redundant, therefore it is deleted (along with it's unittest).
- Ensure all tests pass
- Code review
- I also added parameter doc-string for `run_detection` while I was there
Part of #512

Integrate Message class to run_detection

---

utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

- This PR updates QueueClient (QC) to stop returning _connection (the raw stomp connection).
- This is to avoid direct interaction with stomp outside of the QC
- Code review
- Ensure tests still pass
Fixes #547

Remove _connection returns

---

utils/clients/sftp_client.py
utils/clients/tests/test_sftp_client.py

- This PR adds a `get_filenames` method to `sftp_client` which returns a list of filenames within a given SFTP-server directory which match a given regex
- It additionally refactors server path checking into it's own method (since it is now used across `retrieve` and this new method)
- Lastly, it changes parameter names for paths to be more explicit about the type of path expected (file or directory)
- **Note:** regex' must match the [python re lib specification](https://docs.python.org/2/library/re.html)
- Check that `get_filenames` returns a list of filenames which match the given regex
Fixes #565

Add 'get filenames matching regex' method to SFTPClient

---

scripts/manual_operations/manual_submission.py

- This PR simply changes manual_submission to take `file_path` (i.e. the path to the data to be reduced) from datalocation (as it should be) rather than reductionlocation.
- Ensure reductionlocation is replaced with datalocation
- Check that jobs submitted after being retrieved from the database run as expected
Fixes #562

Change reductionlocation to datalocation

---

scripts/manual_operations/README.md
scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py
utils/clients/database_client.py

* Remove use of old database SQLAlchemy connections in manual_remove.
* Update tests to use Django ORM 
* Ensure the tests pass
* Attempt to use the script to manually remove a run from the database
* see instructions in `scripts/manual_operations/README.md` 
Part of #546 

Remove django ORM from manual_remove.py

---

.travis.yml
WebApp/autoreduce_webapp/reduction_viewer/models.py
message/job.py
message/tests/test_job.py
monitors/run_detection.py
monitors/tests/test_run_detection.py
queue_processors/autoreduction_processor/autoreduction_logging_setup.py
queue_processors/autoreduction_processor/autoreduction_processor.py
queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/autoreduction_processor/tests/test_post_process_admin.py
queue_processors/queue_processor/queue_processor.py
scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py

- This PR refactors the code which handles cases where the overwrite flag is False/None in `post_process_admin.reduce`
- The old implementation was broken, but never used until changes to other areas of the code were changed (#557)
- _Note: to enable this code to run, additional changes were required._
* Due to the Message class having been integrated into manual submission (#542), the data dictionary passed to PPA contained a full set of keys.
* The previous code only checked whether a `message` key existed. This PR extended this by checking whether the value was `None`.
* Additionally, since message cannot be null in the DB, this PR converts a None `message` to `=""`
* This is an open question regarding where in the code this should occur.
___
- Additionally, this PR cherry-picks …

Refactor ppa 'do not overwrite' handling

---

WebApp/autoreduce_webapp/templates/base.html

- Reverts a change made in #550 which caused a bug
- For an unknown reason, this caused jQuery (and potentially other scripts) to not load on run_summary.js (and presumably other pages since the change was in `base.html`).
- Ensure scripts load throughout webapp as expected.
Fixes #589 

Move block scripts sections to it's previous state

---

monitors/tests/test_run_detection.py
systemtests/test_end_to_end.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

- This PR integrates the Message class into `test_end_to_end`.
- This in turn removes the last usage of `queue_client.serialise_data` (outside of tests), and therefore this method was removed as well.
- Ensure tests pass
- Test on dev
- This is part of a series of PRs to integrate the Message class throughout the database.
- After this branch and #584 are merged, only the WebApp is not covered by Message integration.
- This change was attempted before but failed due to not accounting for `facility="ISIS"`
Fixes #512

Integrate Message into test_end_to_end

---

WebApp/autoreduce_webapp/reduction_variables/utils.py

- This PR integrates the Message class into the WebApp.
- The only location queue_client.send was used in the WebApp was found to be `reduction_variables/utils.py`. As such, this is the only location the Message class was required.
**This PR is dependent on changes to the Message class as part of #584.** Namely, the addition of the `cancel` attribute.
- Test on the webapp by re-running a run
**#590 needs to be merged before this can be tested.** This is because without that PR, the functionality to re-run is inaccessible.
- This is (the final?) part of a series of PRs to integrate the Message class throughout the database.
Fixes #512

Integrate Message into the WebApp

---

message/job.py
message/tests/test_job.py
monitors/run_detection.py
monitors/tests/test_run_detection.py

* Fix run submission process
* Add defaults to some Message elements
* checkout this branch on develop ingestion node
* change the most recent run for an instrument in the `C:\lastrun\lastrun.csv` file
* check these runs get re-submitted and go through the webapp / db correctly
This is currently broken on production

reduction_message not null and instrument used

---

build/commands/help.py
build/commands/installs.py
build/install/activemq.bat
build/install/install_services.py
build/test_settings.py
build/tests/validate_installs.py

* Remove the remaining references to icat from the build scripts 
* failed to get all of these in #600 
* run `python setup.py externals` - ensure all works as expected
* run `python setup.py externals -s icat` - ensure this does not do anything / reports an incorrect key given to externals
* code review, ensure ICAT is not mentioned in the build module

Remove all ICAT references from build script

---

scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py

* Add very simple instrument prefix map for instruments that are known issues when manually submitting - MARI and MAPS
* Manual submit a MARI run that is NOT in the autoreduction database using the instrument name `MARI`
* See that the it is found in icat and the file is named `MARxyz.nxs` (not `MARIxyz.nxs`)
This is a simple fix to get things up and running functionally the longer term solution should be investigated and implemented in #602 
No associated issue

Add a simple instrument prefix map to enable manual submission

---

scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py

Allow for removal of many runs for a given instrument as command line argument to match functionality of manual_submission.
Prompts user for validation as safe guard if attempting to remove 10 or more runs.
* Test all unit tests pass
* Manual testing - Try to manually remove one run; many runs, but less than 10; 10 or more runs and check runs are removed.
* No drop in coveralls
Both manual_remove and manual submission need refactoring to bee more python3 and OOP i the future to align with project standards followed throughout the rest of Autoreduction codebase. Note this is a low priority and may be a good new starter issue. 
Fixes #577

Allow for multiple runs to be removed at once

---

WebApp/autoreduce_webapp/autoreduce_webapp/backends.py
WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
WebApp/autoreduce_webapp/autoreduce_webapp/views.py
WebApp/autoreduce_webapp/reduction_viewer/views.py

* Fix errors in Authentication on the webapp
* Ensure the production webapp loads correctly and runs (It might not be able to send messages to compute because that has not been python3 upgraded just yet!)
* When we updated django version (with python 3 upgrade) the function definitions in custom authentication classes changed. We did not pick this up at the time as the development node does not auth through the UOWS. Adding this to the production environment revealed this error
* Also updated to Apache24 as part of this issue.

Ensure that custom UOWS Auth matches updated django API

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html
plotting/plot_handler.py
plotting/tests/test_plot_handler.py

* Allow the webapp to show multiple images for a single reduction job 
* Re-run MAR27036
* After it completes find the run in the dev webapp (afetr switching to this branch)
* Observe multiple plots in the webapp
* Note: this does not handle the drop down menu for plot selection but instead shows all. We will handle the display of this in a separate issue
Fixes #617

Handle multiple images for a single job

---

requirements.txt
scripts/scheduler_ingest.py
utils/clients/database_client.py

Drops the test package requirements from pinned to the current stable.
I noticed this whilst adding `pytest-django` to `requirements.txt` in another branch, the majority of the pinning stems from Python 2 support being dropped in our deps
- CI Tests should pass

Unpin test deps

---

scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py

Used #637 as a guide. Not sure if I should be adding any labels, so please let me know :)
I added mocking for `user_input_check` as without it the test would hang until y/n was entered. (I don't understand why this wasn't happening previously)
I didn't add any type casting as from the docs https://google.github.io/python-fire/guide/#argument-parsing this should be automatic.
The only test failing is `test_find_run` though this was failing already due to my sub optimal setup.
closes #643 

643 fire cli for manual remove

---

scripts/manual_operations/manual_remove.py
scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_remove.py
scripts/manual_operations/tests/test_manual_submission.py
scripts/manual_operations/tests/test_util.py
scripts/manual_operations/util.py

Pulled out the validation on run numbers. This also removed the discrepancy where `manual_submission` would not include the `last_run` and `manual_removal` would. 
@JackEAllen I agree with you, that these 2 scripts could easily be combined and be cleaner overall.
Fixes #607

Pull out some validation from manual_operations into util.py

---

WebApp/autoreduce_webapp/templates/run_summary.html

Added software name - version to run_summary.html below Retrying.
* Code review
* Load the webapp and navigate to a run where there's an entry for that run in the software table.
* Then see that the software name - version is being displayed.
* Also navigate to a run without a software entry and see that "No software data found" is displayed.
Fixes #630 

630 display reduction software in run summary

---

WebApp/autoreduce_webapp/static/css/base.css
WebApp/autoreduce_webapp/templates/run_summary.html

Centred plot when single plot, alligned for 2. on 2+ it wraps, though I am not sure how often a reduction will have more than 2 plots. Can look at different way to handle that scenario?
Also added a small margin to stop the overlap of the plot onto the border of the summary underneath
I tested this by first applying the change in #672 , then duplicated the plot for 67282 locally to get the desired amount of plots.
I guess if you know a run that already has multiple graphs, you could use that instead.
Remember to ctrl f5, like i didnt 🤦 
Fixes #615 

Format plot display

---

plotting/plot_handler.py
plotting/tests/test_plot_handler.py

Probably easiest to review commit by commit in order, instead of all at once.
Added a method to check the local storage for a graph before searching server.
I also added a method to generate the file extension part of the filename regex pattern. This moves 1 existing for loop and meant another wouldn't have to be introduced.
Test names maybe aren't great
I tested this by loading a reduction that produced a graph (MARI 27282) Then I commented out the code to search remotely for the image and restarted the server and made sure the graph was then reloaded when I reopened that reduction.
Fixes #618

Check local storage for graphs

---

model/database/access.py
model/database/tests/test_access.py
queue_processors/queue_processor/queueproc_utils/tests/test_status_utils.py

- `models.database.access.get_status` now raises a ValueError when called with an invalid status_value.
- Added new test in `models/database/access/tests/test_access.py` to test if passing an invalid `status_value` to `access.get_status` raises a `ValueError`.
* Code review to ensure that the unit test is properly formed
* Ensure the unit test passes on Travis
Fixes #606

Add allowed status fields to access.get_status

---

WebApp/autoreduce_webapp/static/css/base.css
WebApp/autoreduce_webapp/static/javascript/help.js
WebApp/autoreduce_webapp/templates/help.html

Implemented a toggle button that filters help topics by a specified category (currently "Usage" and "Questions").
* Code review
* Open the help page then:
* Click on the categories to the right of the search bar to see if help topics for that category appear below.
* Try different combinations of search terms and categories to see if the correct help topics appear.
* Note that "How do I add new instrument variables?" is the only topic in "Usage", the rest are in "Questions". This should be changed before merging.
I wasn't sure which topics, if any, would be considered a question or a usage category.
Fixes #676

Help pages search filter

---

model/message/validation/process.py
model/message/validation/tests/test_process.py
queue_processors/queue_processor/handle_message.py
scripts/manual_operations/manual_submission.py

* This fixes this issue with invalid runs breaking the consumers and forcing them to disconnect
* Enables str RB's to be properly processed
* Manually submit a str RB e.g. `MARI 27252` - This should be skipped and assigned to RB0
* Manually submit a normal RB e.g. `MARI 27037` - This should complete with no issue
* Manually submit a RB 0 e.g. `MARI 26920` - This should be skipped and assigned to RB0
Fixes #673 & Fixes #614 

Fix qp issues

---

build/commands/database.py
build/commands/migrate_settings.py
build/test_settings.py
utils/test_settings.py

- Uses the DB configuration from the generated `credentials.ini`
- Moves the credential generation to happen before the DB config tries to read the generated file
- Removes database-generating commands that require ROOT privileges 
- These seemed to just be duplicating the `mysql < build/database/reset_autoreduction_db.sql` command.
- Locally, they were failing as MySQL does not allow using the `root` user without `sudo`. And I could not find a way to force MySQL to allow that
- Tests should pass
- Check that the following commands execute OK locally 
- python3 setup.py test_settings
- python3 setup.py database 
- Run all tests
I also had to manually run `activemq` on Ubuntu, not sure how that is passing on Travis as I don't see it being manually started from the `.travil.yml`
What …

Fixes to allow successful execution of tests on Ubuntu 18.04

---

.gitignore

Adds a `.keep` file to `WebApp/static/graphs` so that the folder is added to GitHub
Fixes #737 

737 graph dir

---

WebApp/autoreduce_webapp/reduction_viewer/utils.py
WebApp/autoreduce_webapp/templates/admin/graph_instrument.html
WebApp/autoreduce_webapp/templates/experiment_summary.html
WebApp/autoreduce_webapp/templates/fail_queue.html
WebApp/autoreduce_webapp/templates/instrument_summary.html
WebApp/autoreduce_webapp/templates/run_queue.html
WebApp/autoreduce_webapp/templates/run_summary.html
WebApp/autoreduce_webapp/templates/snippets/instrument_status.html
WebApp/autoreduce_webapp/templates/snippets/run_table.html

* Changed the dev database to conform to new status value. See [constrain status model PR](https://github.com/ISISScientificComputing/autoreduce/pull/691).
* Now using `status.verbose_value` (e.g. "Completed") in web app as opposed to `status.value` (e.g "c")
* Code review
* All tests pass
* Open web app and look at the locations of where the run status value will be shown. Check that the full verbose value appears.
* The production database will also need to be altered. Steps I took on the dev database were as follows:
* Change all the status values in `reduction_viewer_status` to char values. There should be only 5 values there.
* Fix all occurrences of status values of greater than 5 in reduction_viewer_reductionrun (there shouldn't be any on production).

Fix status values on webapp

---

WebApp/autoreduce_webapp/templates/submit_runs.html

This PR does:
- Removes duplicated action
- Removes dead link
- Gives a way to show the currently invisible help text
- Adds missing label for accessibility
This PR does not:
- Verify if the additional actions are or were ever working correctly.
Previously:
Now:
I went with the second of the 2 help texts as that was added later in a commit to improve the message.
I have also opened #774 
Fixes #770 

Remove duplicated overwrite action

---

queue_processors/autoreduction_processor/autoreduction_processor.py

Enable the limit reduction script flag when logging the message
The outputs in the `autoreduction_processor.log` are shorter but I still think they are pretty long 
Closes #769

Limit reduction script output

---

requirements.txt
setup.py

This is due to 7.16.1 being the highest one that pip can find on CentOS.
Also added comments to warn about this as travis runs Ubuntu and thus
if `dependabot` opens a PR with an update the builds will pass successfully,
but then fail to install on our environments
On dev queue env:
```
virtualenv /tmp/pr
source /tmp/pr/bin/activate
pip3 install -e .
pip3 install -r requirements.txt
```

Lowers IPython version pin to 7.16.1

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html
plotting/plot_handler.py

The issue was caused by the rendering code falling over when trying to retrieve plot images for:
- Instruments that we don't support plotting at all
- Instruments that have no cached plots
Now renders the page regardless of presence of plot images. If plots are supported for the instrument (seems like only MARI and WISH are according to the code) but not found due to some issue (e.g. locally it was `Authentication failed` because I don't have the correct mount), a warning is displayed:
- Run web-app locally or pull onto dev env. 
- Go into any run on any instrument.
Need to test whether plots still render properly! I couldn't find a run with plots, nor a way to generate them.
The first commit is PyCharm enforcing it's formatting on the changed files. I'm not sure we have a strict …

Fixes runs not displaying due to any error in plot retrieving code

---

queue_processors/queue_processor/test_settings.py

Adds root logger that should be inherited by all `getLogger` calls.
This needs to be deployed on the dev env so that we can see if queue_listener starts logging now.
Fixes #795

Adds config for the `root` logger

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/overview.html
scripts/database_management/reset_database_post_cycle.py

Note: Travis fails because of `sentry_sdk` issue mentioned on teams and referenced here #808
The instrument buttons in the overview page are now populated from `VALID_INSTRUMENTS` from `utils.settings`.
The reset script will also now delete the instrument table.
I had quite a few issues running the script which were out of the scope of this issue, so I have opened #809
Add an instrument to `VALID_INSTRUMENTS` and verify it appears on the overview page
Remove an instrument and verify it is removed from the overview page
Run the database reset script and verify that all instruments are also removed
Run `setup.py database` and verify all models successfully migrated.
closes #766

Control which instruments appear in WebApp

---

queue_processors/daemon.py
queue_processors/queue_processor/README.md
queue_processors/queue_processor/queue_listener.py
queue_processors/queue_processor/queue_listener_daemon.py
queue_processors/queue_processor/tests/test_queue_listener_daemon.py
utils/clients/queue_client.py

- Small cleanup and improving comments in queue_listener.py
- Adds a paragraph about how a cronjob is expected to restart the queue_processor daily
Need to deploy on dev env and restart the `queue_processor` - then check that `logs/queue_processor.log` contains entries from `queue_listener_daemon.py`, and possibly `daemon.py` or `queue_listener.py`
Should be merged after #796 
No associated issue

Makes getLogger consistently use __file__

---

WebApp/autoreduce_webapp/reduction_viewer/utils.py

We catch the base exception allowing it to be properly logged and reported instead of being swallowed and a new exception rethrown.
This should be made more specific in the future, but right now it is more important that we can identify the issue that is being hidden
Resubmit a HRPD run. And the true exception is revealed.
closes #845 

Catch the base exception

---

WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py

See description in #773
Removed certificate also. Panda writes "The certificate for this service is signed by a trusted authority now so you shouldn’t need to import the FITBAWEB1 certificate any more"
* check code changes
*  check that works. On dev environment by changing temporarily change setting `DEVELOPMENT_MODE = True` to `DEVELOPMENT_MODE = False` and check if can login
Fixes #773

Accommodate SOAP/WSDL URL migration

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html

Alters the template for a skipped run
Changes start and end times, duration and hides logs and rerun option
This PR:
Current:
Skipped runs should match updated format
Closes #853 

Cleanup run summary for skipped runs

---

queue_processors/autoreduction_processor/post_process_admin.py

Replaces the map with the 2 manual calls.
Run webapp locally with the fix and resubmit a job with changed parameters. The parameters from the WebApp should now override the standard parameters
Have a look at this comment https://github.com/ISISScientificComputing/autoreduce/issues/870#issuecomment-717188785
Fixes #870 
Release notes added to the release notes PR in commit https://github.com/ISISScientificComputing/autoreduce/commit/9f9f19f5d569a34780c8b79ab7e32faad71d41d0

Implements fix for correctly updating the Python dicts

---

scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
utils/clients/tools/isisicat_prefix_mapping.py
utils/clients/tools/tests/test_isisicat_prefix_mapping.py

This was causing an issue that an instrument missing in VALID_INSTRUMENTS, but valid overall, would fail during submission.
The logic for retrieving the instrument's name from ICAT was changed - `get_icat_instrument_prefix` now takes a full name and returns the ICAT name.
The behaviour where the function would take a list of instruments and return a dictionary of `{fullname: ICAT name}` was never used outside of tests, and has been removed.
The tests were adjusted to test the new behaviour, and the tests testing the multiple return behaviour have been removed.
Fixes #842
- Delete any instrument from your valid instruments, e.g. remove LARMOR
- Try manually submitting a run for it - with the changes it should be successfully submitted
Note: this is based on the release branch and will be …

Fix manual submission failing when instrument is not in VALID_INSTRUMENTS

---

WebApp/autoreduce_webapp/reduction_viewer/views.py

* Changed `sessionId` to `sessionid` in `reduction_viewer.views.index()`
* Load the web app at `/` and see that it does not produces a 500 error
* This was a tricky one to spot!
Fixes #882

Fix sessionid typo which is causing a 500 error on the web app

---

scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py

* Fixed functionality to manually remove a run for a given instrument when multiple versions exists
* Code review
* All tests pass
* Try removing a run using the `manual_remove.py` script for 1 or multiple versions
Fixes #669

Fix manual_remove multiple version bug

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/instrument_summary.html
WebApp/autoreduce_webapp/templates/run_summary.html

Removes the option to rerun jobs through the WebApp if an instrument does not have variables. (As is currently the case only for WISH)
Check that the rerun option in the run-summary and instrument-summary do not appear for WISH only.
closes #846

846 disable rerun for instruments with novariables

---

scripts/backup_reduction_scripts.py

Adds a script that will backup all reduction scripts from the archive - it checks grabs all folders starting with NDX and tries to get a `/user/scripts/autoreduction/reduce.py` and `reduce_vars.py` if it finds one it copies it. If it doesn't it skips the directory.
- Added an account `autoreduce-bot` with write permissions to the repository where the scripts are uploaded. This is currently my fork https://github.com/dtasev/AutoreductionScripts, but as soon as I get access to the main repo I will move it there.
- Updated the VALID_INSTRUMENTS list on the development compute node to match the production ones - the backup script uses it to ensure all are captured.
- And then I removed the dependency on VALID_INSTRUMENTS but I haven't reverted the change on the dev node as it doesn't affect …

Adds a script that will backup all reduction scripts from the archive

---

utils/data_archive/tests/test_file_filter.py

From what I understand from reading the docs `os.listdir` will return in an arbitrary order. The test assumes the order will remain the same, the order is sometimes differing in the workflow vm. So instead we compare the lists ignoring order using a `Counter`. Since the order is irrelevant for the purpose of the function anyway (based on its docstring). 
Fixes #931

Fix the failing test

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html

Combines some queries into single queries, casts a queryset to a list to prevent requerying for instrument summary and run summary pages
Deploy the webapp on master branch.
View the instrument summary and run summary pages (HRPD has a lot of runs so is a good benchmark 78938 especially for run summary page)
Make note of how many queries and time in admin side panel
Redeploy this branch and visit the same pages and view the query differences.
Fixes #940

Optimise queries in webapp

---

model/database/orm.py

Adds a check to `settings.configured` before configuring again. This prevents the exception and thus the logging spam.
Stick a breakpoint in the `except RuntimeError` of  `orm.py::setup_django`, and run `test_manual_remove.py` - the breakpoint won't get triggered.
Optionally run without breakpoints and check that nothing new was logged.
Fixes #787

Check if settings are configured before configuring

---

WebApp/autoreduce_webapp/static/javascript/run_variables.js

* Removed a line of code in `run_variables.js` that references a non-existent element `#previewScript`.
* On the run summary page:
* There should be no error in the console about `#previewScript`
* Checking checkboxes and submitting forms should work.
Fixes #953

Remove broken reference to #previewScript in run_variables.js

---

setup.py

* Use dash_core_components==1.12.1 because of dependency clash seen [here](https://github.com/ISISScientificComputing/autoreduce/runs/1474250570):
```
The conflict is caused by:
autoreduction 20.3 depends on dash_core_components==1.13.0
dash 1.16.3 depends on dash-core-components==1.12.1
```
* Tests pass

Use dash_core_components==1.12.1 for GitHub Actions

---

scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py
systemtests/test_end_to_end.py

- Tries to call the `.delete()` on the `ReducedRun` model. Everything else should get deleted via the on delete cascade.
- It seems like this isn't always the case! Sometimes the DB raises an integrity error - as a workaround the code will revert to it's old behaviour then. This needs further investigation.
- Adds `--delete-all-versions` flag - specifying this means the script will no longer ask you to enter version range. It will just delete all versions for that run. 
- Check that the related foreign key models aren't missing `on_delete=models.CASCADE` (I had a look but possible I missed something)
- This is a huge pain to test manually. The easiest (but not particularly easy) way that I recommend is to:
- Run the script with a debugger attached. 
- Breakpoint before or on …

Use ReduceRun.delete() to delete a run, adds `--delete-all-versions` flag

---

.github/workflows/codeql-analysis.yml

* As seen [here](https://github.com/ISISScientificComputing/autoreduce/pull/977) identical comments are repeated for each language when running `/scan-code`. This PR adds "for language" to each PR comment.
* Also fixed the finished link and ensured the finished comment is added even if the previous steps fail.

code-scan improve pr comment

---

.github/workflows/codeql-analysis.yml

* Run earlier on Monday's to make sure code scanning is complete before starting work.
* Removed on push event to master because 2nd warning here #990 states that on PR event needs to be added too.
* Removed `git checkout HEAD^2` because of warning here  #990
* Removed `/scan-code` PR comment feature in place of workflow [dispatch event](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).
* Code review
* Merge and test features above
Fixes #990

Codeql analysis improvements

---

.github/workflows/codeql-analysis.yml

* Add on push to master event for code scanning workflow
* Fixes `Missing analysis for base commit` warning

Add on push event to master for code scanning workflow

---

build/install/mantid.sh

Swapped the order of two lines. Before, adding the repo came before adding the mantid signing key. Now, adding the signing key comes before adding the repo.
Test by installing mantid:
sudo python setup.py externals -s mantid

Fix adding signing key comes before adding repo

---

plotting/plot_handler.py
plotting/tests/test_plot_handler.py

Instead of joining the paths it was just appending, leading to malformed URI
such as: `[20/Jan/2021 16:25:05] ERROR [app:127] File '/instrument/MARI/RBNumber/RB2000159/autoreducedMAR27877_Ei40.10meV.png' does not exist` - we've dropped a `/` somewhere in #793 
Just adds the dropped `/`. 
`os.path.join` doesn't work as it's on Windows so it makes the path like this: `'/instrument/MARI/RBNumber/RB2000159/autoreduced\MAR27877_Ei40.10meV.png'`
Hard one to test as this only happens when on a Windows machine and accessing the SFTP client which is Linux. Code review should be enough

Fixes retrieving plots from CEPH

---

WebApp/autoreduce_webapp/reduction_viewer/models.py

Adds str dunders to  models meaning the admin page will show more useful text
e.g.
View the admin page and check the models show their name instead of X Object (x)
Fixes #898

Display more information in admin page

---

WebApp/autoreduce_webapp/tests/test_pagination.py
build/database/tests/test_generate_database.py
docker_reduction/mantid/tests/test_mantid_docker_container.py
model/database/tests/test_access.py
model/database/tests/test_orm.py
model/message/validation/tests/test_process.py
monitors/tests/test_run_detection.py
plotting/_plot_handler/tests/test_plot_handler.py
plotting/plot_factory/tests/test_dashapp.py
plotting/plot_factory/tests/test_layout.py
plotting/plot_factory/tests/test_plot_factory.py
plotting/plot_meta_language/tests/test_interpreter.py
plotting/tests/test_plot_handler.py
plotting/tests/test_prepare_data.py
queue_processors/queue_processor/tests/test_queue_listener.py
queue_processors/queue_processor/tests/test_queue_listener_daemon.py
requirements.txt
scripts/manual_operations/tests/test_manual_remove.py
scripts/manual_operations/tests/test_manual_submission.py
scripts/tests/test_scheduler_ingest.py
utils/clients/tests/test_cycle_ingestion_client.py
utils/clients/tests/test_database_client.py
utils/clients/tests/test_django_database_client.py
utils/clients/tests/test_icat_client.py
utils/clients/tests/test_queue_client.py
utils/clients/tests/test_sftp_client.py

Mock is part of the standard library. since `3.3` This removes the dependency from `requirements.txt`
CI Passes

Remove mock dependency

---

WebApp/autoreduce_webapp/autoreduce_webapp/management/commands/add_super.py
WebApp/autoreduce_webapp/reduction_variables/views.py
model/database/tests/test_records.py
model/message/validation/tests/test_stages.py
monitors/tests/test_run_detection.py
plotting/plot_factory/tests/test_trace.py
queue_processors/queue_processor/tests/test_handle_message.py
queue_processors/queue_processor/tests/test_queue_listener.py
queue_processors/queue_processor/tests/test_queue_listener_daemon.py
scripts/backup_reduction_scripts.py
utils/clients/settings/tests/test_client_settings.py
utils/clients/tests/test_queue_client.py
utils/project/structure.py

* Removed method scope imports.
* Fixed code scanning alerts for: Module is imported with 'import' and 'import from'
* Fixed code scanning alerts for: Unused import
* Tests pass
* Code review
* Surely there's a better way of getting the project root without using git in `get_project_root()`? 
Fixes #307

Removes method scope imports and other import related issues

---

WebApp/autoreduce_webapp/autoreduce_webapp/settings.py

Changed STATICFILES_DIRS to 'BASE_DIR, static' so that the web app can be run from any directory (rather than having to run from autoreduction/WebApp/autoreduce_webapp)
Fixes #xyz

Modify STATICFILES_DIRS so web app can be started from any directory

---

scripts/manual_operations/manual_submission.py

Improves error message when manual_submission can't connect to ActiveMQ. I think this is enough to address the 
issue, but suggestions for better error message are welcome.
Check if new message is better/worse than the previous one
Fixes #785

Improves error message when manual_submission can't connect to ActiveMQ

---

requirements.txt
setup.py

There are apparently no usages of ipython or lxml within the project.
I have also removed git from `requirements.txt` as it is already installed via the setup. This is true for other requirements but there are discrepancies between versions which will need to be looked at at some point.
It seems they were both added in relation to a web scraping tool to get data from the beam line page that doesn't exist anymore? #427 
Verify there are no uses of either library
Fixes #1071

Drop unused requirements

---

queue_processors/daemon.py

It keeps the logging messages as well when it's ran from ./restart.sh.
Having the STDOUT messages saves time when something goes wrong - you see the error without having to go to the logs
Run `python queue_processor/queue_listener_daemon.py start` **multiple times** while in the `queue_processors` folder - you should see an error on either the first run (if you already had it running) or consecutive runs. 
The error should be that pidfile already exists.
Fixes #1087

Improves daemon STDOUT messages when ran from CLI

---

queue_processors/queue_processor/settings.py

Adds ARCHIVE_ROOT in QP settings to make changing the archive root folder easier - for testing leave as it is, but if you want to use the real archive just uncomment the one with /isis.
Also Reorders the variables and removes NT branch
- Start ActiveMQ
- Run the queue listener with the settings.py in this PR, without changes. 
- Submit a run (e.g. `python scripts/manual_operations/manual_submission.py MARI 27877`)
- The reduction should fail to find reduce.py and reduce_vars.py at the specified directory
- Uncomment ARCHIVE_ROOT="/isis"
- The reduction should either pass, if you have Mantid, or fail with "Unable to import mantid" if you don't. Both are fine
- Note it might still fail the first time because the MARI reduce.py has a bug in that it doesn't wait for the ScriptRepository to …

Adds ARCHIVE_ROOT in QP settings to make changing the archive root folder easier

---

scripts/nagios_checks/autoreduce_checklastrun.py
setup.py

Removes MySQL requirements from setup.py, this means you should be able to install Autoreduction without installing any MySQL dependencies.
```
python3 -m pip install --user -e autoreduction
```
- Delete `mysql-server` and `libmysqlclient-dev` 
- Create a new virtual environment
- Install Autoreduction again, it should install fine without MySQL being present
Fixes #1103

Removes MySQL requirements from setup.py

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/notification_fixture.json
WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
WebApp/autoreduce_webapp/selenium_tests/pages/component_mixins/navbar_mixin.py
WebApp/autoreduce_webapp/selenium_tests/tests/base_tests.py
WebApp/autoreduce_webapp/templates/header.html

Changes which queries were run to get notifications and added regression tests.
Strictly speaking the notifications are loaded in the header and not the navbar, however whenever the navbar is imported so is the header.
Add notifications and verify they display correctly whether logged in or not. Same as in the tests
Fixes #897

Make notifications visible to admins

---

WebApp/autoreduce_webapp/static/javascript/runs_list.js

Check the element exists before setting onChange and onClick
Prevent automatic submission of filtering. (@dtasev I also found this confusing, and also jarring when the page would reload automatically)
Verify no error on page `/runs/randomstr`
Verify no more automatic submission of filtering
Verify can still be filtered with apply
Fixes #1020

Fix JavaScript error

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/run_with_one_variable.json
WebApp/autoreduce_webapp/selenium_tests/pages/run_summary_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_run_summary.py
WebApp/autoreduce_webapp/templates/run_summary.html
utils/clients/tests/test_queue_client.py

This is based on #1042 and should be merged after
Shows run description in Run Summary. Does NOT rename `run_name` to `run_description`.
Rerun a run with a run description. The description should show up like:
Fixes #1180

Show run description in Run Summary

---

WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
queue_processors/queue_processor/settings.py

Settings now check for `AUTOREDUCTION_PRODUCTION` environment variable, and if so default to the correct production paths.
Code review
Fixes #1121

Automatic production path configuration based on environment var

---

model/message/message.py
model/message/tests/test_message.py

Makes the message.description default = ""
This does not break the Run Summary description visualisation in the web app as empty string is does not pass the `{% if run_description %}` check and that field is not rendered, just like before.
Check https://github.com/ISISScientificComputing/autoreduce/issues/1198
Fixes #1198

Makes the message.description default = ""

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/two_runs_two_vars.json
WebApp/autoreduce_webapp/instrument/views/runs.py
WebApp/autoreduce_webapp/selenium_tests/pages/variables_summary_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_configure_new_runs_integration.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_run_summary.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_see_instrument_variables.py
WebApp/autoreduce_webapp/templates/configure_new_runs.html

PR based on https://github.com/ISISScientificComputing/autoreduce/pull/1174 - some of the changes are from it.
Configure New Runs now shows the correct values for the selected range/experiment.
- Tests are adjusted to expect the correct values (this was previously recorded as comments, e.g. see [here](https://github.com/ISISScientificComputing/autoreduce/pull/1194/files#diff-397f33f8e038ea162756f39b1b6c560e33aac6a47245f3a5cf9d99ecddf81d3eL83-L87))
- Some of the clicks are changed to a `WebDriverWait` to make the tests more reliable.
- Adds fixture `two_runs_two_vars.json` that has 3 runs:
- Run 99999 using variable 1 & 2
- Run 100000 using variable 3 & 4
- This is not used in the tests. 
- The goal is easier testing on PR reviews
```
python setup.py database
python …
```

Configure New Runs page now shows the correct values for the selected range/experiment

---

.pylintrc
WebApp/autoreduce_webapp/reduction_viewer/utils.py
WebApp/autoreduce_webapp/selenium_tests/pages/configure_new_runs_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_run_summary_integration.py
WebApp/autoreduce_webapp/utilities/pagination.py
docker_reduction/mantid/operations.py
model/database/records.py
model/message/message.py
model/message/tests/test_message.py
plotting/plot_factory/trace.py
queue_processors/queue_processor/handle_message.py
queue_processors/queue_processor/instrument_variable_utils.py
queue_processors/queue_processor/reduction/runner.py
queue_processors/queue_processor/reduction/service.py
queue_processors/queue_processor/reduction/tests/test_runner.py
queue_processors/queue_processor/reduction/tests/test_service.py
scripts/database_management/reset_database_post_cycle.py
scripts/manual_operations/tests/test_manual_remove.py
scripts/manual_operations/tests/test_manual_submission.py
utils/clients/queue_client.py
utils/clients/settings/client_settings_factory.py

_copied from issue text_
It seems accessing the DB during testing causes the Selenium tests to operate on 2 different DBs - one seems to be from Pytest, the other one the default from the settings. The cause seems to be that when the reduction runner starts it is a new process, so it doesn't inherit any environment settings that pytest might have changed.
I wasn't able to figure out how to fix that so the faster solution seemed to be to remove the DB access from the reduction runner, and move the required call inside handle_message instead, then pass that information through the Message object
CI tests should pass
Fixes #1231

Removes DB call from reduction runner

---

.vscode/launch.json
WebApp/autoreduce_webapp/instrument/views/runs.py
WebApp/autoreduce_webapp/static/javascript/run_variables.js
WebApp/autoreduce_webapp/templates/submit_runs.html
WebApp/autoreduce_webapp/templates/variables_summary.html

Removes unused JS and CSS imports of Bootstrap-Switch. Usage of this was removed in #1174 but it seems there's some leftover imports.
Refactors `validateRunRange` and `validateBatchRunRange` to not use as much JQuery and be more robust.
`validateBatchRunRange` now enforces `B > A` in a `A-B` range (i.e. B should be a later run)
Tests should pass.
Fixes #1220

Removes bootstrap-switch include

---

WebApp/autoreduce_webapp/instrument/views/runs.py
WebApp/autoreduce_webapp/instrument/views/variables.py
WebApp/autoreduce_webapp/selenium_tests/pages/configure_new_runs_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_configure_new_runs.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_configure_new_runs_integration.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_see_instrument_variables.py
WebApp/autoreduce_webapp/static/javascript/run_variables.js
WebApp/autoreduce_webapp/templates/configure_new_runs.html

Removes the run end field and the creation of a variable signifying "run end".
This should make the variable handling a bit more robust.
Tests should pass and code inspection.
Submit a few variables with different start runs and check that they are active for the correct ranges.
Fixes #1209

Removes Run end from Configure New Runs

---

queue_processors/queue_processor/reduction/runner.py
queue_processors/queue_processor/reduction/tests/test_runner.py

Stops usage of `message.message` as primary error carrier, because it causes this:
Now properly adds error in `message.reduction_log` which makes it look neater, and allows you to view the error in more detail after clicking:

Further improve error capture in runner.py

---

queue_processors/queue_processor/reduction/timeout.py

Adds `*args` to the handle_timeout function, this fixes the exception to be:
```
Exception('Script ran for more than 60 seconds - timed out')
```
rather than
```
TypeError('handle_timeout() takes 1 positional argument but 3 were given')
```
TODO:
Tests should pass.
Change `SCRIPT_TIMEOUT` to 60 or 5 or 1 and run a reduction, it should timeout.
I just put this infinite loop in a reduce.py and ran a reduction
```
import time
def main(input_file, output_dir):
while True:
time.sleep(1)
```

Fixes wrong exception being thrown on Timeout, adds args to the handle_timeout func

---

WebApp/autoreduce_webapp/templates/run_summary.html
WebApp/autoreduce_webapp/templates/snippets/run_variables.html

Previously it was part of the `run_variables.html` which gets rendered only if the run has variables.

Makes the "Back to <instrument>" button always appear 

---

queue_processors/queue_processor/handle_message.py
queue_processors/queue_processor/queue_listener.py
queue_processors/queue_processor/tests/test_handle_message.py
queue_processors/queue_processor/tests/test_queue_listener.py
utils/clients/queue_client.py

Adds a connected `contextmanager` to automatically connect/disconnect from DB.
This is done before handling a data_ready message, and should remove the "MySQL server has gone away" timeout message.
Also show FQDN in logs instead of hostname as it makes more sense to humans
Fixes #1256

Manage DB connection lifetime during Message processing & show FQDN in logs instead of hostname

---

WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
model/database/orm.py

Adds a check that will remove dead connections before actual access to the database is attempted.
This should prevent the "MySQL server has gone away" errors after the QP has remained connected to the DB for a long time - by default MySQL stops the connection after 8 hours.
The `CONN_MAX_AGE = 60` setting is also added to:
- Reduce the number of connections, now the DB connection will be alive for 1 min and should be reused in a large chunk of the reduction prep code (e.g. creating db objects etc). The default behaviour is 0 which means the connections get closed after every request
- The connection will now expire on the client and be removed, a long time before MySQL has a chance to time it out.
Tests should pass. And we'll see production tomorrow

Prevent "MySQL server has gone away" timeout

---

.vscode/launch.json
autoreduce.code-workspace
queue_processors/queue_processor/__init__.py
utils/clients/queue_client.py
utils/clients/tests/test_queue_client.py

Adds stdout logger handler - this means all output will now be printed to stdout as well. Can be quite handy now that the stdout is captured by Singularity.
Adds a check in queue client to prevent accidental connections to production. It will show an error if you have `AUTOREDUCTION_PRODUCTION` declared but are connecting to 127.0.0.1, as well as if you don't have it but aren't connecting to 127.0.0.1 or something with "dev" in the name.
Adds a Python attach configuration for vscode, and extends the workspace to include the ansible and containers repos.

Adds stdout logger & a check in queue client to prevent accidental connections to production

---

WebApp/autoreduce_webapp/templates/snippets/run_variables.html
WebApp/autoreduce_webapp/templates/submit_runs.html

Removes duplicate run_description ids inside the form field. The `name="run_description"` is important for the POST method.
Tests should pass.
Submit a re-run locally and test that the description is properly set

Removes duplicate run_description ids

---

queue_processors/queue_processor/reduction/service.py
queue_processors/queue_processor/reduction/tests/test_service.py

Adds a / at the end of the temp_dir path.  Some reduction scripts just do `output_dir + str` which breaks output copying, as all output files end up being `/tmp/abcedfgFILENAME.nxs` rather than `/tmp/abcedfg/FILENAME.nxs`
Fixes #1286

Convert TemporaryReductionDirectory path to property and append /

---

WebApp/autoreduce_webapp/reduction_viewer/views.py

Check if the `?next` URL is safe before using it as `redirecturl` from UOWS.
The safe URLs are the one listed in `ALLOWED_HOSTS`, which are usually localhost & the host domain.
Fixes #1288

Check if the `?next` URL is safe before using it as redirecturl from UOWS

---

.github/actions/build-autoreduction/action.yml
.gitignore
WebApp/autoreduce_webapp/autoreduce_webapp/settings.py
WebApp/autoreduce_webapp/autoreduce_webapp/urls.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_run_summary.py
build/commands/database.py
plotting/plot_handler.py
plotting/tests/test_plot_handler.py
setup.py

Removes SFTP Client from plot_handler - a benefit of hosting the webapp on CentOS is that we can just copy the files from CEPH without a need for SFTPing. This could be bad if we move away from hosting on Linux/SCD Cloud but that's probably not worth worrying about.
Also adds Whitenoise as Django middleware to serve staticfiles (CSS/JS/plot images). This is a workaround to:
- Plot files being copied locally to render in the web app. 
- Apache not being able to access that location anymore, as the web app is on a different machine
The proper fix would be to move the staticfiles storage on a separate, common location. This would be necessary when we have >1 hosts for the web app.
These changes are currently live on the production env. 
Check that the production website loads assets and …

Remove SFTP Client from plot_handler, add whitenoise to serve staticfiles AR-1291

---

.github/workflows/run-tests.yml
.yapfignore
requirements.txt
setup.py

Updated all 3 dash libraries in one go to prevent clashes.
Remove duplicated requirements
Tests should pass 
@dtasev 
`yapf` would like for the `setup.py` list to be in 5 lines instead of 1 per requirement. 
That is:
```python
setup_requires = [
'attrs==20.3.0',
'dash==1.20.0',
'dash_html_components==1.1.3',
'dash_core_components==1.16.0',
'docker==5.0.0',
'Django==3.2',
'django_extensions==3.1.2',
'django_plotly_dash==1.6.3',
'django-user-agents==0.4.0',
'filelock==3.0.12',
'fire==0.4.0',
'gitpython==3.1.14',
'nexusformat==0.6.1',
'numpy==1.19.2',
'pandas==1.1.5',
'plotly==4.14.3',
'pytz==2021.1',
'PyMySQL==1.0.2',
'pysftp==0.2.9',
'python-icat==0.18.0',
'requests==2.25.1',
'service_identity==18.1.0',
'stomp.py==6.1.0',
'suds-py3==1.4.4.1',
'PyYAML==5.4.1'
]
```
To this:
```python …
```

Update requirements and setup AR-1271

---

WebApp/autoreduce_webapp/static/css/base.css

Added slight margin below run summary back button.
Before:
After:
* Test the run summary page to see the margin

Add slight margin below back button

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/run_with_multiple_variables.json
WebApp/autoreduce_webapp/instrument/models.py
WebApp/autoreduce_webapp/selenium_tests/pages/component_mixins/rerun_form_mixin.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_rerun_jobs_integration_multivars.py
WebApp/autoreduce_webapp/templates/run_summary.html
model/database/access.py
queue_processors/queue_processor/instrument_variable_utils.py
queue_processors/queue_processor/reduction/runner.py
queue_processors/queue_processor/reduction/service.py
queue_processors/queue_processor/reduction/tests/test_service.py
queue_processors/queue_processor/tests/test_instrument_variable_utils.py
queue_processors/queue_processor/variable_utils.py

Stops the queue processor from converting everything to string before saving in the DB - this means the original types are now kept. Adds tests for the different supported variable types to check that they are properly shown on the web app and stored in the DB as expected
**Adds back replacement of the reduction arguments** - currently only the values in reduce_vars are used and are never replaced. The fix will be deployed in production after this PR is merged. Adds test for this so it doesn't happen again.
Fixes AR-1283

Keep real types in the database objects' values AR-1283 AR-1329

---

autoreduce_qp/queue_processor/reduction/service.py
autoreduce_qp/queue_processor/reduction/tests/test_service.py
autoreduce_qp/queue_processor/tests/test_handle_message.py
setup.py

Removes using `chardet` to try and find the encoding as the implementation was broken - it just checked one character `chardet.detect(file_raw.read(32))["encoding"]`. For this to work properly, that specific character had to be non-ASCII.
This may be leftover from Python 2.7
It seems that there is no need for this anymore. Just doing `open` and reading in the file works, and can handle any UTF-8 characters.
Adds some tests with emojis to ensure utf-8 compatibility.
Tests should pass. Code review

Read in file as non-binary UTF-8 | AR-1420

---

autoreduce_qp/autoreduce_django/fixtures/run_with_multiple_variables.json
autoreduce_qp/model/database/access.py
autoreduce_qp/model/database/tests/test_access.py

Fixes how the most relevant batch run is found, in order to have the correct version number. It now matches all run numbers. If any run number is mismatching then this is a new batch run.
1. Run all the things, the order is not important: `Run queue listener`, `Run webapp`, `Run REST API`. All 3 must be running as submitting a runs uses all 3
2. Go to http://127.0.0.1:8000/tokens/ and generate a new token for the `(super)` user
3. Go to INTER and click Submit Batch Run button
4. Submit run for 63125-63130, change some of the description/params just to test that they get changed
- You'll need to create reduce.py/reduce_vars.py first! Full instructions here https://github.com/ISISScientificComputing/autoreduce/wiki/Start-here-(getting-the-code---installation)#are-you-going-to-be-submitting-r …

Fixes how the most relevant batch run is found

---

autoreduce_qp/queue_processor/reduction/runner.py
autoreduce_qp/queue_processor/reduction/tests/test_runner.py

Replace temp output file for tests with patches, as temp output file is not used in production

remove temp output from runner, replace tests with patches

---

.github/workflows/run-tests.yml
container/qp_mantid_python36.D
setup.py

Update tests to Python 3.8 to allow for Django 4.x
Uses Django>=3.2.10 to allow use on 3.7 and below

Update django 4

---

autoreduce_qp/queue_processor/reduction/runner.py
autoreduce_qp/queue_processor/reduction/service.py
autoreduce_qp/queue_processor/reduction/tests/test_service.py
autoreduce_qp/queue_processor/variable_utils.py
autoreduce_qp/systemtests/test_end_to_end.py

Uses the script text from message.reduction_script should be used instead of loading the reduce.py
- write the script text to a tmp file, which can then be loaded by ReductionScript.load
If message.reduction_script is None the reduce.py gets loaded in anyway by the create_reduction_run_record func. (already implemented)

1056 use message reduction script ar 1056

---

autoreduce_qp/model/database/access.py
autoreduce_qp/model/database/records.py
autoreduce_qp/model/database/tests/test_access.py
autoreduce_qp/model/database/tests/test_records.py
autoreduce_qp/queue_processor/handle_message.py
autoreduce_qp/queue_processor/reduction/process_manager.py
autoreduce_qp/queue_processor/reduction/runner.py
autoreduce_qp/queue_processor/reduction/tests/common.py
autoreduce_qp/queue_processor/reduction/tests/test_process_manager.py
autoreduce_qp/queue_processor/reduction/tests/test_runner.py
autoreduce_qp/queue_processor/reduction/tests/test_utilities.py
autoreduce_qp/queue_processor/reduction/utilities.py
autoreduce_qp/queue_processor/tests/test_handle_message.py
autoreduce_qp/systemtests/base_systemtest.py

Fix `message.software` not being utilised properly as it is hardcoded to Mantid in multiple places. (AR-1230)
Lays groundwork for Supporting multiple reduction softwares (AR-1324)
- Makes 'Software' var in Message a dict {name: "", version:""}
- String of Software will be used to fetch the correct image to run the reduction with (Currenly only runner-mantid:6.2.0 is a valid image)

1230 remove hardcoded software ar 1230

---

.github/workflows/run-tests.yml
autoreduce_qp/queue_processor/confluent_consumer.py
setup.py

Refactor consumer to use kafka_utils config in autoreduce_utils

---

autoreduce_qp/queue_processor/reduction/service.py

This error is occuring on reduction reruns:
```
"[09/Aug/2022 20:21:05] ERROR [autoreduce_qp.queue_processor.reduction:101] Traceback (most recent call last):
File "/venv/lib/python3.8/site-packages/autoreduce_qp/queue_processor/reduction/runner.py", line 92, in _do_reduce
reduce(reduction_dir, temp_dir, datafiles, reduction_script, self.reduction_arguments, reduction_log_stream)
File "/venv/lib/python3.8/site-packages/autoreduce_qp/queue_processor/reduction/service.py", line 229, in reduce
reduction_dir.create()
File "/venv/lib/python3.8/site-packages/autoreduce_qp/queue_processor/reduction/service.py", line 55, in create
os.makedirs(self.path, mode=0o777, exist_ok=False)
File "/venv/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
FileExistsError: [Errno 17] File exists: …
```

Allow reductiondir existing

---

environment.yml

Add toml to mamba as it is not currently installed by Mantid (will be in future)
Fixes #xyz

Add toml to mamba

---

autoreduce_qp/queue_processor/reduction/service.py

Revert back to disutils and os.makeidrs for systemtest permissions (but keep exist_ok=True).
If permission issues happen again with production runner-mantid, this is the change that probably will have done that. I believe it should be okay though

Fix tests by mostly reverting changes

---

autoreduce_qp/autoreduce_django/settings.py

I checked that the queue-processor has the DJANGO_SECRET_ENV environment variable, in the k8s repo we have a secrets file [here](https://github.com/autoreduction/k8s/blob/b50f70f6506a6c3eab2d688713008e473f00191a/ansible/roles/queue_processor/templates/qp-secret.yaml#L8), and that is given the queue-processor in the k8s repo aswell as a secretRef in this [file](https://github.com/autoreduction/k8s/blob/b50f70f6506a6c3eab2d688713008e473f00191a/ansible/roles/queue_processor/templates/deployment.yaml#L31)
Just code review here.
Fixes #1483 
No release notes as not user facing and just a security update.

Use the DJANGO_SECRET_ENV environment variable for key

---

.github/workflows/run-tests.yml

We no longer need to publish to PyPi, so we will stop.
Code review
Fixes #1484 
Release notes updates are not necessary.

Remove publishing of PyPi package autoreduce-qp
