QueueProcessors/AutoreductionProcessor/autoreduction_logging_setup.py
QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
QueueProcessors/AutoreductionProcessor/post_process_admin.py
QueueProcessors/AutoreductionProcessor/settings.py.template

The changes below fix the issues on the development nodes, and improve our ability to catch similar problems in the future.
After this issue is reviewed and merged, we should try to keep the dev node up-to-date with changes. I'll add a git pull request template that covers the manual testing that we should be doing to validate our changes before merging

Fix issues on the development nodes

---

QueueProcessors/AutoreductionProcessor/autoreduction_processor.py
QueueProcessors/AutoreductionProcessor/autoreduction_processor_daemon.py
QueueProcessors/AutoreductionProcessor/daemon.py
QueueProcessors/AutoreductionProcessor/post_process_admin.py
QueueProcessors/AutoreductionProcessor/timeout.py
QueueProcessors/QueueProcessor/base.py
QueueProcessors/QueueProcessor/daemon.py
QueueProcessors/QueueProcessor/orm_mapping.py
QueueProcessors/QueueProcessor/queue_processor.py
QueueProcessors/QueueProcessor/queue_processor_daemon.py
QueueProcessors/QueueProcessor/utils/instrument_utils.py
QueueProcessors/QueueProcessor/utils/instrument_variable_utils.py
QueueProcessors/QueueProcessor/utils/messaging_utils.py
QueueProcessors/QueueProcessor/utils/reduction_run_utils.py
QueueProcessors/QueueProcessor/utils/status_utils.py
QueueProcessors/QueueProcessor/utils/variable_utils.py
Scripts/Build/test/test_pylint.sh

Improve the pylint script to fail the travis build if it fails
Also reduce code duplication in pylint script
---
Ensure that the package changes work when running the queues (on the dev nodes)

Improve pylint script

---

utils/test_helpers/data_archive_creator.py

* To make testing less painful, lets add the data archive creator in a separate PR
* Code review the new archive creator and have a play with it. Check if it is:
* Easy to use (intuitive)
* Creates what is expected
* Bug free

Add the data-archive creator to utils package

---

.travis.yml
Scripts/Build/generate_testing_database.sh
Scripts/Build/migrate_test_settings.sh
Scripts/Build/populate-reduction_viewer-db.sql
Scripts/Build/test/test_db_generation.py
Scripts/Build/travis-db-setup.sql

* Generate some test data to add to the local test database
* This is to be merged before #11 
* Run the `generate_test_database.py` script locally *(you might have to run the migrate_test_settings.py script first)*
* Ensure the new database generation tests run correctly on travis

Add files for database data generation and testing

---

build/commands/help.py
build/commands/migrate_settings.py
build/commands/start.py
build/database/generate_database.py
build/tests/test_db_generation.py
build/tests/test_pylint.sh

This will resolve the pylint errors in the build directory.
Fixes #124

Pylint errors in build

---

WebApp/autoreduce_webapp/manage.py
WebApp/autoreduce_webapp/tests/test_input_processing.py
WebApp/autoreduce_webapp/tests/utils.py
WebApp/autoreduce_webapp/utilities/input_processing.py
WebApp/example_reduce.py
WebApp/example_reduce_vars.py
build/tests/test_pylint.sh

Pylint: webapp misc

---

WebApp/autoreduce_webapp/reduction_viewer/admin.py
WebApp/autoreduce_webapp/reduction_viewer/models.py
WebApp/autoreduce_webapp/reduction_viewer/utils.py
WebApp/autoreduce_webapp/reduction_viewer/view_utils.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
build/tests/test_pylint.sh

Pylint Webapp reduction viewer

---

WebApp/autoreduce_webapp/test_files/ExistingTestInstrument1/reduce.py
WebApp/autoreduce_webapp/test_files/ExistingTestInstrument1/reduce_vars.py
WebApp/autoreduce_webapp/test_files/InactiveInstrument/reduce.py
WebApp/autoreduce_webapp/test_files/InactiveInstrument/reduce_vars.py
WebApp/autoreduce_webapp/test_files/duplicate_var_reduce/reduce.py
WebApp/autoreduce_webapp/test_files/duplicate_var_reduce/reduce_vars.py
WebApp/autoreduce_webapp/test_files/empty_script/reduce.py
WebApp/autoreduce_webapp/test_files/empty_script/reduce_vars.py
WebApp/autoreduce_webapp/test_files/new_instrument/reduce.py
WebApp/autoreduce_webapp/test_files/new_instrument/reduce_vars.py
WebApp/autoreduce_webapp/test_files/reduce.py
WebApp/autoreduce_webapp/test_files/reduce_vars.py
WebApp/autoreduce_webapp/test_files/syntax_error/reduce.py
WebApp/autoreduce_webapp/test_files/syntax_error/reduce_vars.py
WebApp/autoreduce_webapp/test_files/valid/reduce.py
WebApp/autoreduce_webapp/test_files/valid/reduce_vars.py
build/tests/test_pylint.sh

Pylint webapp test files

---

utils/archive_explorer/archive_explorer.py
utils/archive_explorer/file_filter.py
utils/archive_explorer/tests/test_archive_explorer.py
utils/archive_explorer/tests/test_file_filter.py
utils/data_archive_creator/data_archive_creator.py

The archive explorer is designed to be able to provide an easy way to obtain data from the isis data archive.
this allows us to remove a lot of the functionality and cached values that were previously stored in the data archive creator. This means that we can now use this searching functionality with both a real and a fake archive
* Ensure that the new unit tests for the archive explorer and file filter run and pass.
* Ensure the new files have 100% test coverage in coveralls
* [Creating a fake archive](https://github.com/ISISScientificComputing/autoreduce/wiki/Testing-and-validating#creating-a-fake-data-archive) locally. Create an `AchiveExplorer` and check it find all the value you expect. 
Fixes #139

Data archive explorer

---

WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/colour_table_rows.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/common_helpers.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/get_user_name.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/natural_time_difference.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/replace.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/variable_type.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/view.py
build/tests/test_pylint.sh

* Code review
* Test that the template tags in the web app still render
Fixes #128

Pylint webapp template tags

---

build/commands/installs.py
build/commands/start.py
build/install/activemq.bat
build/install/activemq.sh
build/test_settings.py
build/tests/validate_installs.py
build/utils/build_logger.py

Updated the ActiveMQ version to ensure download does not fail (generate activemq executable name in settings file)
Fixes #161

Update activemq version

---

utils/data_archive/data_archive_creator.py

Small change to remove the need for sleeps in `DataArchiveCreator`
* Code review should be fine to test this
Fixes #148

Update modification time instead of sleep

---

.travis.yml
scripts/manual_submission_script/tests/test_manual_submission.py
scripts/mysql_dump/tests/test_cycle_database_reset.py
setup.py

Scripts tests have now been added to the coverage in .travis.yml. I have also added tests covering the manual submission script.
Fixes #182

scripts test coverage

---

build/database/generate_database.py

Fixes #223
To test:
* Check that the Database setup works on https://github.com/ISISScientificComputing/autoreduce/wiki/Setup where mysql password is set 
* check code

Allow mysql password with newer version of mysql

---

monitors/health_check.py
monitors/tests/test_health_check.py

* send JSON data rather than dict to ActiveMQ
* Add try catch to make this debugging easier in future

Resolve issue with Health check crashing when submitting runs

---

monitors/end_of_run_monitor.py

Update global observer object when we restart the  queue

EoRM health check hotfix

---

WebApp/autoreduce_webapp/reduction_viewer/views.py

* Make instruments list in alphabetical order
* Load the webapp
* See that the front page (run list) has the instruments in alphabetical order
*No associated issue*

Order instruments on run page alphabetically

---

WebApp/autoreduce_webapp/templates/help.html

* Correct closing div tags
* Remove requirement to be staff to see some help
* Update out of date data location
* Visit the updated help pages `/help/`
* Observe the updates to the text in the section `Where does my reduced data go?`
Fixes #284

Updates to help pages

---

WebApp/autoreduce_webapp/reduction_viewer/views.py

Added optimisations to the run loading code.
Ensure the webapp still works and that runs load faster.
Fixes #309

Improved run loading performance for the new webapp

---

QueueProcessors/AutoreductionProcessor/post_process_admin.py
QueueProcessors/AutoreductionProcessor/tests/test_post_process_admin.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/help.html
WebApp/autoreduce_webapp/templates/run_summary.html

* Updated documentation pages to use ISIS compute / IDAaaS
Ensure documentation makes sense
Fixes #334

update data access docs

---

.travis.yml

Remove specific versioning for mysql in travis script

Mysql version

---

QueueProcessors/AutoreductionProcessor/post_process_admin.py
WebApp/autoreduce_webapp/manage.py
monitors/test_settings.py
setup.py
utils/clients/abstract_client.py

Minimal Implementation of Sentry web-hooks to look at extent of coverage throughout application.
Purposely cause an error within application and check it is logged by Sentry.
you can access Sentry here:
http://172.16.114.151:9000/sentry/internal/
Test Sentry collects errors from production environment
Fixes #342

sentry integration

---

.travis.yml
WebApp/autoreduce_webapp/autoreduce_webapp/admin.py
WebApp/autoreduce_webapp/autoreduce_webapp/backends.py
WebApp/autoreduce_webapp/autoreduce_webapp/icat_cache.py
WebApp/autoreduce_webapp/autoreduce_webapp/icat_communication.py
WebApp/autoreduce_webapp/autoreduce_webapp/queue_processor.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/get_user_name.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/natural_time_difference.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/replace.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/view.py
WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
WebApp/autoreduce_webapp/autoreduce_webapp/uows_client.py
WebApp/autoreduce_webapp/autoreduce_webapp/urls.py
WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
WebApp/autoreduce_webapp/autoreduce_webapp/views.py
WebApp/autoreduce_webapp/reduction_variables/models.py
WebApp/autoreduce_webapp/reduction_variables/utils.py
WebApp/autoreduce_webapp/reduction_viewer/models.py

* Fix django migrations in web app
* This includes several changes to ensure python3 compatibility around the web app
* Fix start build step to use local version of python
* Ensure travis passes all build steps without error and the database has been constructed corrected (initial db_test is successful)
* Added additional database test back in first to ensure test db is valid
Fixes #406

Python 3 - Build Steps

---

WebApp/autoreduce_webapp/tests/test_input_processing.py
monitors/run_detection.py
monitors/tests/test_run_detection.py
paths/tests/test_collections.py
paths/tests/test_path.py
queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/daemon.py
queue_processors/queue_processor/queueproc_utils/instrument_variable_utils.py
queue_processors/queue_processor/test_settings.py
scripts/database_management/tests/test_cycle_database_reset.py
scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py
utils/clients/settings/tests/test_client_settings.py
utils/clients/settings/tests/test_client_settings_factory.py
utils/clients/tests/test_abstract_client.py
utils/clients/tests/test_icat_client.py
utils/data_archive/data_archive_creator.py
utils/data_archive/tests/test_data_archive_creator.py
utils/data_archive/tests/test_file_filter.py

* Resolve the **UNIT** test failures throughout the project
* Ensure that all the unit tests pass on Travis
Fixes #398

Python3 - Unit tests

---

WebApp/autoreduce_webapp/autoreduce_webapp/icat_cache.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/get_user_name.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/replace.py
WebApp/autoreduce_webapp/autoreduce_webapp/templatetags/view.py
WebApp/autoreduce_webapp/autoreduce_webapp/test_settings.py
WebApp/autoreduce_webapp/autoreduce_webapp/view_utils.py
WebApp/autoreduce_webapp/reduction_variables/utils.py
WebApp/autoreduce_webapp/reduction_variables/views.py
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/experiment_summary.html
WebApp/autoreduce_webapp/templates/fail_queue.html
WebApp/autoreduce_webapp/templates/instrument_summary.html
WebApp/autoreduce_webapp/templates/instrument_variables.html
WebApp/autoreduce_webapp/templates/overview.html
WebApp/autoreduce_webapp/templates/run_summary.html
WebApp/autoreduce_webapp/templates/snippets/instrument_status.html
WebApp/autoreduce_webapp/templates/snippets/run_table.html
WebApp/autoreduce_webapp/templates/snippets/variables.html
build/install/icat.bat
build/install/icat.sh

* Ensure all pages display in the webapp
* Ensure all functionality is correct in the webapp
* Open the webapp locally and point it to the dev database (set credentials.ini to development credentials)
* Ensure all static content is displayed as expected
* Try all the buttons, links, etc.
* This is not the final test of this, it will be re-tested on the development branch to assess if it is fully functional as part of merging in python 3
Fixes #426

py3 manual testing webapp

---

monitors/run_detection.py
monitors/tests/test_run_detection.py

* Swap to h5py 
* Ensure tests pass with different nxs data file structure
Fixes #433

Use h5py for nexus reading

---

scripts/mantid/properties.py
scripts/mantid/tests/test_properties.py
utils/test_settings.py

* Add script to generate mantid properties file and unit test
* Add missing instruments to test_settings
* Ensure unit tests pass
* This script was used for production and develop envs so I am confident that it is working correctly
Fixes #449

Add Mantid properties generation script and test

---

plotting/plot_meta_language/plot_types/README.md
plotting/plot_meta_language/plot_types/example.yaml

First attempt at plotting meta language for visualisation
This only covers the the graph layout. I'm not sure what, if anything?, you would really need to define for the data lines @JackEAllen can we discuss this tomorrow and how this will work with the plotting factory - might require us to update the design doc
Read through documentation and decide if:
* This is going to capture enough information
* The layout of the .yaml is clear and understandable  
* See minor updates to drawio diagram for design
Fixes #474

plotting meta language design

---

requirements.txt
setup.py
utils/clients/settings/client_settings_factory.py
utils/clients/settings/tests/test_client_settings_factory.py
utils/clients/sftp_client.py
utils/clients/tests/test_sftp_client.py
utils/test_credentials.ini
utils/test_settings.py

SFTP Client implemented using pysftp, extending abstract_client.py.
Framework based on existing client classes (e.g. database_client, queue_client, icat_client).
Currently this is a **work in progress**
Fixes #470 

Implement SFTP Client

---

plotting/README.md

Creation of brief documentation specifying ideal data format for plotting.
*  Ensure documentation is grammatically correct
*  Ensure documentation and example script are understandable
*  Ensure data format is mutually agreed upon by all members of the team
Fixes #472

472 plotting format

---

queue_processors/queue_processor/queueproc_utils/status_utils.py
queue_processors/queue_processor/queueproc_utils/tests/compare_db_object.py
queue_processors/queue_processor/queueproc_utils/tests/test_status_utils.py
queue_processors/queue_processor/queueproc_utils/tests/test_variable_utils.py
queue_processors/queue_processor/queueproc_utils/variable_utils.py

* Add tests to `queue_proc_utils.variable_utils`
* Add tests to `queue_proc_utils.status_utils`
* code review of tests  
*No associated issue - internal change to testing so no updates required to release notes*

Add tests to queue_proc_utils

---

scripts/mantid/tests/test_properties.py

* Update docstrings in scripts/mantid
* Improved one test to cover use case better
* Code review 
* Passes travis
Part of #514
**Internal change so no need to update release notes**

Improve docstrings in scripts / mantid

---

requirements.txt

* pin pylint to particular version (2.4.4)
* pylint passes on travis

Pin pylint to older version 2.4.4

---

systemtests/test_end_to_end.py

* Change the system tests to use the new DjangoORM 
* Ensure the system tests still run successfully
Part of #546

Change system tests to use Dajngo ORM

---

systemtests/test_end_to_end.py

Reverts ISISScientificComputing/autoreduce#569
Builds seem to be breaking after merging this so reverting

Revert "Change system tests to use Dajngo ORM"

---

systemtests/test_end_to_end.py

Reverts ISISScientificComputing/autoreduce#571

Revert "Revert "Change system tests to use Dajngo ORM""

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html

Hotfix to plotting integration in webapp

---

scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
utils/clients/__init__.py
utils/clients/django_database_client.py
utils/clients/tests/test_django_database_client.py

* Remove old way of accessing database in manual_submission
* Add function for retrieving reduction_runs in django db client
* Attempt to manually submit a run already in the database using the manual_submission script.
* Ensure that it reaches the webapp / database successfully  
Part of #546

Django ORM manual submission

---

queue_processors/queue_processor/queue_processor.py
queue_processors/queue_processor/tests/test_queue_processor.py
systemtests/test_end_to_end.py

- This PR integrates the Message class into the entire `queue_processor`
- Ensure tests pass
- Test on dev
- This is part of a series of PRs to integrate the Message class throughout the database.
- Previous, un-merged PRs attempted this is various areas of the code base, but were unsuccessful due to changes that had to be made to other areas of the code (see #567)
Fixes #512

Integrate Message into queue_processor

---

scripts/manual_operations/tests/test_manual_submission.py
utils/clients/__init__.py

* Revert changes made to include shortcuts in clients
* Unit tests 

Remove shortcuts to clients

---

.travis.yml
message/job.py
message/tests/test_job.py
queue_processors/autoreduction_processor/autoreduction_processor.py
queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/autoreduction_processor/tests/test_autoreduction_processor.py
queue_processors/autoreduction_processor/tests/test_post_process_admin.py
queue_processors/queue_processor/queueproc_utils/messaging_utils.py
queue_processors/queue_processor/queueproc_utils/tests/test_messaging_utils.py
scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
systemtests/test_end_to_end.py
utils/clients/queue_client.py

- This PR integrates the Message class into `autoreduction_processor` and `messaging_utils`.
- In doing so, a 'cancel' attribute has been added to the Message class.
- Ensure tests pass
- Test on dev
- This is part of a series of PRs to integrate the Message class throughout the database.
- **I rebased following #581 being merged. Many of the 'files changed' are actually changes from that branch**
Fixes #512

Integrate Message into autoreduction_processor and messaging_utils

---

message/job.py
message/tests/test_job.py

Add facility default in message class

---

message/job.py
message/tests/test_job.py
message/validation/process.py
message/validation/stages.py
message/validation/tests/test_process.py
message/validation/tests/test_stages.py
message/validation/tests/test_validators.py
message/validation/validators.py

* Add implementation and tests for the data_ready validation 
* Ensure unit tests pass
* Code review
* Needs 100% coverage of new lines
* The next PR will be integrating the validation to pre-data_ready 
Part of  #513

Add validation for data ready

---

model/database/access.py
model/database/tests/test_access.py
queue_processors/queue_processor/queueproc_utils/reduction_run_utils.py

* Refactored functionality for finding highest run number to access
* Add test
* Unit test passing should be enough for this
* This is a pre-issue to finishing off the remaining image plotting work

Refactor find highest version

---

.gitignore
.travis.yml
Documentation/release-notes/20-1.md
WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/run_summary.html
plotting/plot_handler.py
plotting/tests/test_plot_handler.py
utils/clients/sftp_client.py

* This should make the webapp run without commenting out the plotting code. 
* Inspect the webapp to see if an image is displayed.
* Currently this should be possible for any MARI runs, although remember data is wiped from the dev node twice a day so if the image does not appear, you may need to re-run.

Add plot_location use to webapp

---

.coveragerc

Updates coverage RC file to get a better result from the CI test. Just some minor improvements I noticed whilst waiting for my tests to finish
See commits for details on each change.
Check coverage still works and produces sensible results

Update coverage rc

---

WebApp/autoreduce_webapp/static/javascript/tours/run_summary_tour.js
WebApp/autoreduce_webapp/templates/run_summary.html

Extended Virtual interactive tour to run summary page
* Code review
* Ensure all descriptions are grammatically correct.
* Ensure that tour descriptions are ordered in logical manner i.e descriptions are linear to how a user may navigate through webpage.
Fixes #658

implement virtual interactive tour for run summary page

---

setup.py

Unpin the version of Twisted in `setup.py`
Fixes #665

665 upgrade twisted

---

setup.py

Reverts ISISScientificComputing/autoreduce#666

Revert "665 upgrade twisted"

---

setup.py

fix twisted security issue

---

WebApp/autoreduce_webapp/templates/help.html

Refactor help pages to fix minor grammatical errors and fix outdated hyperlinks
Proof read help pages, ensuring all hyperlinks take you to the expected location
Fixes #678

Refactor help page content

---

WebApp/autoreduce_webapp/static/javascript/create_tour.js
WebApp/autoreduce_webapp/static/javascript/tours/instrument_summary_tour.js
WebApp/autoreduce_webapp/templates/instrument_summary.html

Extended Virtual interactive tour to instrument summary page
* Code review
* Ensure all descriptions are grammatically correct.
* Ensure that tour descriptions are ordered in logical manner i.e descriptions are linear to how a user may navigate through webpage.
Fixes 656

656 interactive tour instrument summary

---

queue_processors/autoreduction_processor/README.md

* Correctly added explanation of what autoreduction processor is responsible for
* Read through changes for grammar etc.
*No associated issue*

Update the readme for the autoreduction_processor module

---

build/install/activemq.bat
build/test_settings.py

Link activemq install documentation 
* check added code comments and how they read
Fixes #703

Link activemq install documentation

---

WebApp/autoreduce_webapp/templates/help.html

* Comment out search functionality in help pages
* Open webapp local and ensure the help page does NOT have a search bar
Fixes #701

Comment out search bar in help page

---

WebApp/autoreduce_webapp/static/css/base.css
WebApp/autoreduce_webapp/static/css/help.css
WebApp/autoreduce_webapp/static/javascript/help.js
WebApp/autoreduce_webapp/templates/help.html

Created a side menu/index for topics displayed on Autoreduction Webapp Help page.
And on a small screen size:
* Code review
* Index/side mentu is well placed and structured
* All links navigate user to correct section of help page.
* Menu links work with filters
* Ensure the page functions and looks good on different screen sizes
* I wasn't sure how to make anchor links work on page load since the anchor links are generated by some JS code which is run after the page would scroll to any anchor link.
Fixes #677

Help page index menu

---

queue_processors/autoreduction_processor/post_process_admin.py
queue_processors/autoreduction_processor/tests/test_post_process_admin.py

Place processes which save additional directories if specified in reduction script into a method outside of reduce()
Add unit tests to check additional save directories functionality behaves as expected.
* Code review
* All unit tests within post_process_admin.py pass
* No drop in coveralls
Fixes #638

638 ppa Save Additional Directories

---

WebApp/autoreduce_webapp/static/css/base.css
WebApp/autoreduce_webapp/templates/overview.html

Changed the instrument button spacing on the overview page for smaller screen sizes.
Old:
New:
* Code review
* Open overview page and change screen size to see if there's consistent instrument button spacing.

Fix overview page instrument button spacing

---

build/generate_apache_wsgi.py
model/message/message.py
plotting/plot_meta_language/interpreter.py
plotting/prepare_data.py
queue_processors/autoreduction_processor/post_process_admin.py
scripts/database_management/reset_database_post_cycle.py
scripts/manual_operations/manual_submission.py
utils/clients/connection_exception.py
utils/clients/cycle_ingestion_client.py
utils/clients/database_client.py
utils/clients/django_database_client.py
utils/clients/icat_client.py
utils/clients/queue_client.py
utils/clients/settings/client_settings.py
utils/clients/settings/client_settings_factory.py
utils/clients/sftp_client.py
utils/data_archive/data_archive_creator.py
utils/data_archive/file_filter.py

Many small amendments to meet pylint 2.6 requirements throughout Autoreduction Codebase.
The changes are primarily amending and/or disabling where appropriate the following pylint checks:
* raise-missing-from (mainly amendments)
* super-with-arguments (applying pylint disables)
Please note that we should go through these changes again to see if we can easily amend  pylint `super-with-arguments` requirements where possible as to simply disabling them (which is a quick fix i am putting in place to allow builds to pass again) - I will attach a link to the issue for doing this later
* code review
* Ensure unit tests pass (they should all pass as i incrementally made a change then ran corresponding unit tests for each script modified) - please note some tests cannot run locally and should be …

Ammendments to meet pylint 2.6 requirements

---

WebApp/autoreduce_webapp/static/css/base.css

Changes font colour of header welcome and footer navbar text to be in line with WCAG 
Load home page, ctrl+f5. Check colours are within WCAG contrast
Fixes #663 

Contrast fix

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/templates/instrument_summary.html

* Fixes #762 by making the [instrument_summary](https://github.com/ISISScientificComputing/autoreduce/blob/762-instrument-not-found-when-instrument-exists/WebApp/autoreduce_webapp/reduction_viewer/views.py#L302) page output a more contextual error message "No runs found for instrument.",  "Instrument not found." and "An unexpected error has occurred when loading the instrument.". More could be added in the future if needed.
* Slight code cleanup of [reduction_viewer/views.py](https://github.com/ISISScientificComputing/autoreduce/blob/762-instrument-not-found-when-instrument-exists/WebApp/autoreduce_webapp/reduction_viewer/views.py)
* Code review 
* All unit tests pass
* Load an unknown instrument on the web app, e.g. `/instrument/ABCDE`. It should output "Instrument not found."
* Load an …

Instrument not found issue and views.py code cleanup

---

WebApp/autoreduce_webapp/templates/help.html
WebApp/example_reduce.py

See #725 . NULL or "Copy raw data" scripts added for Muon instruments, see e.g. (needs to be within ISIS firewall) \\isis\inst$\NDXMUSR\user\scripts\autoreduction . In addition Max Skoda also requested this, and this script added for POLREF, SURF and INTER instruments also.
Replaced out-of-date example_reduce.py scripts, with a copy of this null script.
* Test that copy raw data script works, e.g. by submitting a HIFI, MUSR or POLREF job to the dev environment
* Check the comments in the code are they easy to understand, and the example code
Fixes #725

NULL autoreduction script/step for copy raw data for Muon instruments

---

WebApp/autoreduce_webapp/static/javascript/help.js
WebApp/autoreduce_webapp/templates/help.html

* Commented out a bit of JavaScript in help.js which was causing #788 
* Added comments pointing to relevant issue https://github.com/ISISScientificComputing/autoreduce/issues/701 where the search bar code has been disabled
* Code review
* All tests pass
* Go to the help page and test if the navigation sidebar works
Fixes #788

Fix broken help navigation

---

WebApp/autoreduce_webapp/reduction_viewer/views.py
WebApp/autoreduce_webapp/static/css/help.css
WebApp/autoreduce_webapp/static/javascript/help.js
WebApp/autoreduce_webapp/templates/help.html

Adds the statuses to the help page. With a few accessibility changes (Missing header levels) and js clean up.
Please feedback on explanations. I am not a writer
closes #768

Add statuses to help page

---

requirements.txt
setup.py

Pins all package versions.
See that builds pass. If you want to - delete your python environment and re-install the packages with `pip install -e . && pip install -r requirements.txt`
I've taken the versions from my local conda environment, and once we merge this we should start getting dependabot prs to update them (like #813)
closes #808

Pins package versions to allow dependabot to look for upgrades

---

model/database/access.py

See #835 
That can now submit jobs such as `python manual_submission.py HRPD 78271` and where instrument not currently in database.
Fixes #835

Can't submit jobs after database cleared

---

WebApp/autoreduce_webapp/reduction_viewer/models.py

Quick fix to allow reruns will open an issue (#852) to reinforce this and identify why the software was not included originally.
Verify that a run can be resubmitted in the WebApp
closes #850 

Allow blank software

---

WebApp/autoreduce_webapp/static/javascript/tours/instrument_summary_tour.js
WebApp/autoreduce_webapp/static/javascript/tours/navbar_tour.js
WebApp/autoreduce_webapp/static/javascript/tours/run_summary_tour.js
WebApp/autoreduce_webapp/templates/instrument_summary.html
WebApp/autoreduce_webapp/templates/run_summary.html

- Appends the navbar tour to the other page tours
- Makes full stops consistent
- Make the navbar tour more general (i.e. doesn't make it specific to the end of the tour)
Run the WebApp tours by clicking 'Take a Tour'
- Very minor change
- Accidently pushed these commits to master originally! I've since reverted them. Sorry 😅
Fixes #860

Tweak WebApp tours

---

scripts/manual_operations/manual_submission.py
scripts/manual_operations/tests/test_manual_submission.py
utils/clients/tools/isisicat_prefix_mapping.py

Enable OSIRIS to work with manual_submission.
Also tied up doc of method changed in recent PR.
* test that can submit e.g. `python manual_submission.py OSIRIS 144376`
* test readability
Not sure how easy it is to regression test this with the current mocking setup. Hence left this as is, but ideas welcome
Fixes #884

Can't submit OSIRIS run with manual_submission

---

documentation/release-notes/20-1.md
documentation/release-notes/20-3.md

PR for adding release notes to 20_3 and to be backported into release branch Autoreduction-v20.3
This PR is assigned to all who has contributed to the code since cycle 2019/04 | 11 Feb 2020​ | 27 Mar 2020​
Check content reads OK and matches work that has been done since 19.4

release notes for 20_3

---

model/message/message.py
model/message/validation/stages.py
model/message/validation/tests/test_stages.py
monitors/run_detection.py
monitors/test_settings.py

Changes check in message.py - error is now raised towards caller.
Handles and logs validation failure in `run_detection.py`.
Removes unused INSTRUMENTS variable from the `monitors.test_settings`
Fixes #892
Fixes #893

Errors in message.validate are now raised to caller; handle and log validation failure in run_detection.py

---

WebApp/autoreduce_webapp/templates/help.html

See #902 
* Check updated help text reads and displays OK
Fixes #902

Made ref to FileBrowser access on webapp

---

scripts/manual_operations/README.md
scripts/manual_operations/manual_remove.py
scripts/manual_operations/tests/test_manual_remove.py

* Added feature to input a range (e.g 0-5) to remove runs
* Code cleanup
* Added new tests
* Improved comments
* Improved text output
* Find a run with multiple versions and try removing
* Code review
* Test pass 
Fixes #912

Add manual remove by range

---

setup.py

* Removed == from comment in `setup.py` to stop confusing dependabot 
* As seen here https://github.com/ISISScientificComputing/autoreduce/pull/968

Remove == from comment to stop confusing dependabot

---

.github/workflows/run-tests.yml

Run coveralls after pytest in GitHub Actions workflow

Run coveralls after pytest

---

model/message/validation/tests/test_validators.py
model/message/validation/validators.py

901 improve rb validation

---

build/database/tests/test_generate_database.py
model/database/tests/test_orm.py
scripts/tests/test_scheduler_ingest.py

Quick fixes for some of the 80+ code scanning warnings

Minor assertion code scanning fixes

---

.coveragerc
README.md
build/tests/test_db_generation.py
model/database/orm.py
model/database/tests/test_orm.py
requirements.txt
setup.py

* Updated badge in readme from travis to GitHub actions
* Travis related comments changed to GH actions
* Test branch condition in `model/database/orm.py` that was ignored because of travis.
* Updated wiki
* Ignore migrations generated code in coverage
* Tests pass
* Code review

Update travis references to GitHub Actions

---

WebApp/autoreduce_webapp/reduction_viewer/view_utils.py

Split as cannot add regression tests due to blocking issues #1036 and #986
Instruments will now be reenabled if the reduce.py is found again.
closes #954 

#954: Reenable disabled instruments

---

setup.py

No longer used anywhere
Closes #718

Removes twisted from required packages

---

utils/settings.py

Renames get_str to get_setting and adds docstring
Code review
Fixes #1039

Renames get_str to get_setting and adds docstring

---

WebApp/autoreduce_webapp/instrument/utils.py
WebApp/autoreduce_webapp/static/javascript/create_tour.js
queue_processors/queue_processor/reduction/tests/test_runner.py
scripts/tests/test_scheduler_ingest.py
utils/project/tests/test_structure.py

A number of code scanning fixes:
- Imprecise asserts
- Removed a commented out test (Seemed to match the test 2 above)
- Unused import
- JavaScript change
Ignored as much WebApp stuff as possible while big Web PR is in progress.

Code scanning fixes

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json

vscode defaults

---

queue_processors/queue_processor/queue_listener.py

Logs when an exception happens before the connection is successful, e.g. if the connection itself fails due to credentials
Fixes #1122

Add logging Connection Exception

---

WebApp/autoreduce_webapp/templates/snippets/run_variables.html

Run webapp locally, but the gif above captures the changes well.
Code review.
Fixes #1178

Moves Reset button tooltips to accessible icons

---

WebApp/autoreduce_webapp/instrument/views/runs.py
WebApp/autoreduce_webapp/templates/configure_new_runs.html

Small refactor to remove unnecessary parameters from the POST method.
Tests should pass.
Fixes #1203 

Remove params from Configure New Runs POST

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/one_run_plot.json
WebApp/autoreduce_webapp/selenium_tests/pages/run_summary_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_run_summary.py
WebApp/autoreduce_webapp/templates/run_summary.html
plotting/plot_handler.py
plotting/tests/test_plot_handler.py

Adds tests for Run Summary page
Check that builds pass. Code review
Fixes #1167 

Adds plot tests for Run Summary page

---

WebApp/autoreduce_webapp/templates/configure_new_runs.html
WebApp/autoreduce_webapp/templates/submit_runs.html

These images capture the changes well.
Rerun jobs:
Before:
After 
Configure new runs:
Before:
After:
Fixes #1207

Makes the info boxes more accessible

---

WebApp/autoreduce_webapp/selenium_tests/README.md
WebApp/autoreduce_webapp/selenium_tests/pages/help_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/rerun_jobs_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/run_summary_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/runs_list_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_help_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_rerun_jobs.py
WebApp/autoreduce_webapp/static/css/help.css
WebApp/autoreduce_webapp/static/javascript/help.js
WebApp/autoreduce_webapp/templates/help.html

* Code review
* Tests pass
* Start up webapp and check that the search, categories field and sidebar work as expected. Also test with different screen sizes.
* Check that styling doesn't look off
Fixes #699 
Fixes #987

Improve help page

---

WebApp/autoreduce_webapp/instrument/views/runs.py
WebApp/autoreduce_webapp/templates/help.html
WebApp/autoreduce_webapp/templates/snippets/run_variables.html
WebApp/autoreduce_webapp/templates/submit_runs.html

I have removed the front end option to trigger overwrite but kept the message the same until we decide how/if we will reimplement it after consultation mentioned in #956 
I have added the explanation to the help page for reference but this could possibly belong somewhere else?
Feedback on explanation encouraged
Small change so code review
Fixes #957 

Remove overwrite

---

WebApp/autoreduce_webapp/selenium_tests/pages/help_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/rerun_jobs_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/run_summary_page.py
WebApp/autoreduce_webapp/selenium_tests/pages/runs_list_page.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_help_page.py

Fixes some pylint errors that snuck on master.
Code inspection test should pass

Fixes pylint errors

---

WebApp/autoreduce_webapp/autoreduce_webapp/settings.py

Navigate to pages that produce logs e.g. submit_runs. verify output to webapp.log
Fixes #1216

webapp logging

---

queue_processors/queue_processor/handle_message.py
queue_processors/queue_processor/tests/test_handle_message.py

Similar to #1243 - but this time for when RunVariable saving fails for whatever reason.

Improves the error saved in the DB when saving the run variables fails

---

queue_processors/queue_processor/tests/test_variable_utils.py
queue_processors/queue_processor/variable_utils.py

Renames and adds test for the function
Fixes a [silly mistake](https://github.com/ISISScientificComputing/autoreduce/pull/1247/files#diff-2deffcb168460a0227eacf030bbb827aa20615fed1413a3cda0b8b1ab3a354e9R138) and adds tests for the function
Discovered & already live on the production webapp

Fixes passing "name" (str) instead of name (local var)

---

model/message/message.py
monitors/run_detection.py
utils/clients/queue_client.py

Adds a missing f to an f-string
Adds facility="ISIS" to the run_detection
Use the hostname as connection ID (though I'm not sure we can see that anywhere)
Fixes #xyz

Minor fixes discovered during deploying smoke testing

---

WebApp/autoreduce_webapp/autoreduce_webapp/urls.py

This prevents an error for skipped runs whose RB number is -1000, or anything < 0

Adds a converter for a negative number in the URL

---

WebApp/autoreduce_webapp/reduction_viewer/utils.py
WebApp/autoreduce_webapp/static/javascript/run_variables.js

Replace square brackets off of input. 
Convert software to string before sending in message
Fixes #1278

validateList remove square brackets

---

.github/workflows/run-tests.yml
README.md
scripts/manual_operations/tests/test_manual_submission.py

Test Codecov

---

WebApp/autoreduce_webapp/autoreduce_webapp/fixtures/run_with_multiple_variables.json
WebApp/autoreduce_webapp/selenium_tests/pages/component_mixins/rerun_form_mixin.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_rerun_jobs_integration_multivars.py
WebApp/autoreduce_webapp/static/css/base.css
WebApp/autoreduce_webapp/static/javascript/run_variables.js
WebApp/autoreduce_webapp/templates/run_summary.html
queue_processors/queue_processor/tests/test_variable_utils.py
queue_processors/queue_processor/variable_utils.py

#1308 broke the saving of Boolean vars - this fixes it. Expands the tests to include bool vars as well.
Tests should pass. 
Fixes #xyz

Fixes boolean variables failing to save AR-1333

---

.vscode/extensions.json
.vscode/launch.json
.vscode/tasks.json
WebApp/autoreduce_webapp/instrument/views/variables.py
WebApp/autoreduce_webapp/selenium_tests/driver.py
WebApp/autoreduce_webapp/selenium_tests/tests/test_rerun_jobs_integration_multivars.py
queue_processors/queue_processor/instrument_variable_utils.py
queue_processors/queue_processor/tests/test_instrument_variable_utils.py
queue_processors/queue_processor/tests/test_variable_utils.py

Fix bad comparison of real type vs string

---

setup.py

Adds chardet and updates version

---

autoreduce_qp/queue_processor/__init__.py
autoreduce_qp/queue_processor/handle_message.py
autoreduce_qp/queue_processor/queue_listener.py
autoreduce_qp/queue_processor/reduction/runner.py
autoreduce_qp/queue_processor/reduction/service.py
autoreduce_qp/queue_processor/settings.py

Removes `dictConfig` in favour of `basicConfig`. Sends all logging into a single file and `stdout`, changed from separate files for each app.
Fixes #xyz

Removes dictConfig and just sets up a basicConfig

---

.vscode/tasks.json
autoreduce_qp/systemtests/base_systemtest.py
autoreduce_qp/systemtests/test_activemq_reconnect.py
autoreduce_qp/systemtests/test_end_to_end.py
autoreduce_qp/systemtests/utils/data_archive.py
setup.py

Remove dependency on autoreduce-scripts

---

autoreduce_qp/queue_processor/queue_listener.py
autoreduce_qp/queue_processor/tests/test_queue_listener.py
setup.py

Adjust queue_listener to stomp 7

---

autoreduce_qp/queue_processor/handle_message.py
autoreduce_qp/queue_processor/tests/test_handle_message.py
setup.py

Revert DataLocation removal

---

autoreduce_qp/model/database/access.py
autoreduce_qp/model/database/records.py
autoreduce_qp/model/database/tests/test_access.py
autoreduce_qp/model/database/tests/test_records.py
autoreduce_qp/queue_processor/handle_message.py
autoreduce_qp/queue_processor/queue_listener.py
autoreduce_qp/queue_processor/reduction/exceptions.py
autoreduce_qp/queue_processor/reduction/process_manager.py
autoreduce_qp/queue_processor/reduction/tests/test_service.py
autoreduce_qp/queue_processor/reduction/tests/test_utilities.py
autoreduce_qp/queue_processor/tests/test_handle_message.py
autoreduce_qp/queue_processor/variable_utils.py

Update get_script_and_arguments() to fetch the contents of any raw GitHub file URLs and store them within the arguments dictionary as the values of the appropriate corresponding key.

1473 drop down menu ar 1473

---

autoreduce_qp/queue_processor/reduction/service.py
container/qp_mantid_python36.D
setup.py

Remove unused ascii encode from when project used older version of Python.

Remove ascii encode

---

ansible/roles/run/queue-processor/start/vars/production.yml
ansible/roles/run/queue-processor/stop/tasks/main.yml
autoreduce_qp/queue_processor/queue_listener.py

Uses logger in main and updates ansible roles

---

.vscode/launch.json
autoreduce_qp/queue_processor/reduction/process_manager.py
autoreduce_qp/queue_processor/reduction/service.py
container/qp_mantid_python36.D
setup.py

Fixes environment being overwritten in process-manager

---

autoreduce_qp/queue_processor/reduction/process_manager.py
autoreduce_qp/queue_processor/reduction/tests/common.py
autoreduce_qp/queue_processor/reduction/tests/test_runner.py
autoreduce_qp/systemtests/test_end_to_end.py

Bind the current user's home directory to the home directory of the container (isisautoreduce)

Bind home to isisautoreduce home

---

container/qp_mantid_python36.D
setup.py

increment version

---

.github/workflows/run-tests.yml

Bump codecov-action to v2

---

autoreduce_qp/systemtests/test_activemq_reconnect.py

Switch from subprocess to docker-py for creating Docker container of ActiveMQ

switch from subproccess to native tooling (docker-py)

---

setup.py

increment versions

---

autoreduce_qp/systemtests/test_activemq_reconnect.py
setup.py

Increment db

---

setup.py

Increment db version

---

.github/workflows/codeql-analysis.yml

There was a warning in our analysis checks that stated it would stop working in December without this work.
Tests pass
Not relevant here

Update codeql-analysis to more up to date version

---

pyproject.toml

Fix missing reference to README

---

.github/workflows/codeql-analysis.yml
.github/workflows/run-tests.yml

Update checkout to v3

---

container/runner_py38_mantid.Dockerfile

Added some dependencies to the dockerfile
build the docker file, run python, import mantid, import maptlotlib, both should be imported successfully.

Add matplotlib and libgl1-mesa-glx as dependencies

---

autoreduce_qp/queue_processor/reduction/process_manager.py

Add .mantid to mount into runner-mantid

---

.github/workflows/docker-qp.yml

Create github action to build queue-processor

---

autoreduce_qp/model/database/access.py

Allows queue-processor to better handle the MySQL has gone away and disconnected due to timeout errors.
tested manually with James and I
No release notes as it is a stability fix.

Add check for mysql gone away
